//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Plan_PlanInfor。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Plan_PlanInfor")]
    [Serializable]
    public partial class Mes_Plan_PlanInfor : Entity
    {
        #region Model
        private int _ID;
        private string _Factory;
        private string _PlanCode;
        private string _MaterialProNo;
        private string _MaterialCode;
        private string _Version;
        private int _CompleteNum;
        private int _PlanNum;
        private string _Unit;
        private DateTime? _BeginTime;
        private DateTime? _EndTime;
        private int _PlanStatus;
        private string _Creater;
        private DateTime _CreatedTime;
        private string _Modifier;
        private DateTime? _ModifiedTime;
        private string _OrderNo;
        private string _OrderType;
        private int? _WorkShopID;
        private int? _PlanType;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 工厂
        /// </summary>
        [Field("Factory")]
        public string Factory
        {
            get { return _Factory; }
            set
            {
                this.OnPropertyValueChange("Factory");
                this._Factory = value;
            }
        }
        /// <summary>
        /// 计划编号
        /// </summary>
        [Field("PlanCode")]
        public string PlanCode
        {
            get { return _PlanCode; }
            set
            {
                this.OnPropertyValueChange("PlanCode");
                this._PlanCode = value;
            }
        }
        /// <summary>
        /// 产品编码
        /// </summary>
        [Field("MaterialProNo")]
        public string MaterialProNo
        {
            get { return _MaterialProNo; }
            set
            {
                this.OnPropertyValueChange("MaterialProNo");
                this._MaterialProNo = value;
            }
        }
        /// <summary>
        /// 产品简称
        /// </summary>
        [Field("MaterialCode")]
        public string MaterialCode
        {
            get { return _MaterialCode; }
            set
            {
                this.OnPropertyValueChange("MaterialCode");
                this._MaterialCode = value;
            }
        }
        /// <summary>
        /// 版本
        /// </summary>
        [Field("Version")]
        public string Version
        {
            get { return _Version; }
            set
            {
                this.OnPropertyValueChange("Version");
                this._Version = value;
            }
        }
        /// <summary>
        /// 完成数量
        /// </summary>
        [Field("CompleteNum")]
        public int CompleteNum
        {
            get { return _CompleteNum; }
            set
            {
                this.OnPropertyValueChange("CompleteNum");
                this._CompleteNum = value;
            }
        }
        /// <summary>
        /// 计划数量
        /// </summary>
        [Field("PlanNum")]
        public int PlanNum
        {
            get { return _PlanNum; }
            set
            {
                this.OnPropertyValueChange("PlanNum");
                this._PlanNum = value;
            }
        }
        /// <summary>
        /// 单位
        /// </summary>
        [Field("Unit")]
        public string Unit
        {
            get { return _Unit; }
            set
            {
                this.OnPropertyValueChange("Unit");
                this._Unit = value;
            }
        }
        /// <summary>
        /// 计划开始时间
        /// </summary>
        [Field("BeginTime")]
        public DateTime? BeginTime
        {
            get { return _BeginTime; }
            set
            {
                this.OnPropertyValueChange("BeginTime");
                this._BeginTime = value;
            }
        }
        /// <summary>
        /// 计划结束时间
        /// </summary>
        [Field("EndTime")]
        public DateTime? EndTime
        {
            get { return _EndTime; }
            set
            {
                this.OnPropertyValueChange("EndTime");
                this._EndTime = value;
            }
        }
        /// <summary>
        /// _1-创建;2-下达;3-在制;4-完工;5-关闭
        /// </summary>
        [Field("PlanStatus")]
        public int PlanStatus
        {
            get { return _PlanStatus; }
            set
            {
                this.OnPropertyValueChange("PlanStatus");
                this._PlanStatus = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Creater")]
        public string Creater
        {
            get { return _Creater; }
            set
            {
                this.OnPropertyValueChange("Creater");
                this._Creater = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreatedTime")]
        public DateTime CreatedTime
        {
            get { return _CreatedTime; }
            set
            {
                this.OnPropertyValueChange("CreatedTime");
                this._CreatedTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Modifier")]
        public string Modifier
        {
            get { return _Modifier; }
            set
            {
                this.OnPropertyValueChange("Modifier");
                this._Modifier = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ModifiedTime")]
        public DateTime? ModifiedTime
        {
            get { return _ModifiedTime; }
            set
            {
                this.OnPropertyValueChange("ModifiedTime");
                this._ModifiedTime = value;
            }
        }
        /// <summary>
        /// 订单编号
        /// </summary>
        [Field("OrderNo")]
        public string OrderNo
        {
            get { return _OrderNo; }
            set
            {
                this.OnPropertyValueChange("OrderNo");
                this._OrderNo = value;
            }
        }
        /// <summary>
        /// 订单单别
        /// </summary>
        [Field("OrderType")]
        public string OrderType
        {
            get { return _OrderType; }
            set
            {
                this.OnPropertyValueChange("OrderType");
                this._OrderType = value;
            }
        }
        /// <summary>
        /// 工作车间
        /// </summary>
        [Field("WorkShopID")]
        public int? WorkShopID
        {
            get { return _WorkShopID; }
            set
            {
                this.OnPropertyValueChange("WorkShopID");
                this._WorkShopID = value;
            }
        }
        /// <summary>
        /// 计划类别
        /// </summary>
        [Field("PlanType")]
        public int? PlanType
        {
            get { return _PlanType; }
            set
            {
                this.OnPropertyValueChange("PlanType");
                this._PlanType = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.Factory,
				_.PlanCode,
				_.MaterialProNo,
				_.MaterialCode,
				_.Version,
				_.CompleteNum,
				_.PlanNum,
				_.Unit,
				_.BeginTime,
				_.EndTime,
				_.PlanStatus,
				_.Creater,
				_.CreatedTime,
				_.Modifier,
				_.ModifiedTime,
				_.OrderNo,
				_.OrderType,
				_.WorkShopID,
				_.PlanType,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._Factory,
				this._PlanCode,
				this._MaterialProNo,
				this._MaterialCode,
				this._Version,
				this._CompleteNum,
				this._PlanNum,
				this._Unit,
				this._BeginTime,
				this._EndTime,
				this._PlanStatus,
				this._Creater,
				this._CreatedTime,
				this._Modifier,
				this._ModifiedTime,
				this._OrderNo,
				this._OrderType,
				this._WorkShopID,
				this._PlanType,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Mes_Plan_PlanInfor");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ID = new Field("ID", "Mes_Plan_PlanInfor", "");
            /// <summary>
            /// 工厂
            /// </summary>
            public readonly static Field Factory = new Field("Factory", "Mes_Plan_PlanInfor", "工厂");
            /// <summary>
            /// 计划编号
            /// </summary>
            public readonly static Field PlanCode = new Field("PlanCode", "Mes_Plan_PlanInfor", "计划编号");
            /// <summary>
            /// 产品编码
            /// </summary>
            public readonly static Field MaterialProNo = new Field("MaterialProNo", "Mes_Plan_PlanInfor", "产品编码");
            /// <summary>
            /// 产品简称
            /// </summary>
            public readonly static Field MaterialCode = new Field("MaterialCode", "Mes_Plan_PlanInfor", "产品简称");
            /// <summary>
            /// 版本
            /// </summary>
            public readonly static Field Version = new Field("Version", "Mes_Plan_PlanInfor", "版本");
            /// <summary>
            /// 完成数量
            /// </summary>
            public readonly static Field CompleteNum = new Field("CompleteNum", "Mes_Plan_PlanInfor", "完成数量");
            /// <summary>
            /// 计划数量
            /// </summary>
            public readonly static Field PlanNum = new Field("PlanNum", "Mes_Plan_PlanInfor", "计划数量");
            /// <summary>
            /// 单位
            /// </summary>
            public readonly static Field Unit = new Field("Unit", "Mes_Plan_PlanInfor", "单位");
            /// <summary>
            /// 计划开始时间
            /// </summary>
            public readonly static Field BeginTime = new Field("BeginTime", "Mes_Plan_PlanInfor", "计划开始时间");
            /// <summary>
            /// 计划结束时间
            /// </summary>
            public readonly static Field EndTime = new Field("EndTime", "Mes_Plan_PlanInfor", "计划结束时间");
            /// <summary>
            /// _1-创建;2-下达;3-在制;4-完工;5-关闭
            /// </summary>
            public readonly static Field PlanStatus = new Field("PlanStatus", "Mes_Plan_PlanInfor", "_1-创建;2-下达;3-在制;4-完工;5-关闭");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Creater = new Field("Creater", "Mes_Plan_PlanInfor", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Plan_PlanInfor", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Modifier = new Field("Modifier", "Mes_Plan_PlanInfor", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ModifiedTime = new Field("ModifiedTime", "Mes_Plan_PlanInfor", "");
            /// <summary>
            /// 订单编号
            /// </summary>
            public readonly static Field OrderNo = new Field("OrderNo", "Mes_Plan_PlanInfor", "订单编号");
            /// <summary>
            /// 订单单别
            /// </summary>
            public readonly static Field OrderType = new Field("OrderType", "Mes_Plan_PlanInfor", "订单单别");
            /// <summary>
            /// 工作车间
            /// </summary>
            public readonly static Field WorkShopID = new Field("WorkShopID", "Mes_Plan_PlanInfor", "工作车间");
            /// <summary>
            /// 计划类别
            /// </summary>
            public readonly static Field PlanType = new Field("PlanType", "Mes_Plan_PlanInfor", "计划类别");
        }
        #endregion
    }
}