//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Tra_OutStock。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Tra_OutStock")]
    [Serializable]
    public partial class Mes_Tra_OutStock : Entity
    {
        #region Model
		private int _ID;
		private string _Barcode;
		private string _SN;
		private string _PackSN;
		private string _MaterialProNo;
		private string _MaterialCode;
		private string _OrderType;
		private string _OrderNumber;
		private int? _ResNum;
		private string _OptName;
		private int _OrgID;
		private DateTime? _ScanTime;
		private int? _Status;

		/// <summary>
		/// MappingId
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 员工信息Id
		/// </summary>
		[Field("Barcode")]
		public string Barcode
		{
			get{ return _Barcode; }
			set
			{
				this.OnPropertyValueChange("Barcode");
				this._Barcode = value;
			}
		}
		/// <summary>
		/// 角色信息ID
		/// </summary>
		[Field("SN")]
		public string SN
		{
			get{ return _SN; }
			set
			{
				this.OnPropertyValueChange("SN");
				this._SN = value;
			}
		}
		/// <summary>
		/// 外箱SN生成原则(YYYYMMDDHHMMSSS)
		/// </summary>
		[Field("PackSN")]
		public string PackSN
		{
			get{ return _PackSN; }
			set
			{
				this.OnPropertyValueChange("PackSN");
				this._PackSN = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialProNo")]
		public string MaterialProNo
		{
			get{ return _MaterialProNo; }
			set
			{
				this.OnPropertyValueChange("MaterialProNo");
				this._MaterialProNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get{ return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 订单单别
		/// </summary>
		[Field("OrderType")]
		public string OrderType
		{
			get{ return _OrderType; }
			set
			{
				this.OnPropertyValueChange("OrderType");
				this._OrderType = value;
			}
		}
		/// <summary>
		/// 订单单号
		/// </summary>
		[Field("OrderNumber")]
		public string OrderNumber
		{
			get{ return _OrderNumber; }
			set
			{
				this.OnPropertyValueChange("OrderNumber");
				this._OrderNumber = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ResNum")]
		public int? ResNum
		{
			get{ return _ResNum; }
			set
			{
				this.OnPropertyValueChange("ResNum");
				this._ResNum = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OptName")]
		public string OptName
		{
			get{ return _OptName; }
			set
			{
				this.OnPropertyValueChange("OptName");
				this._OptName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OrgID")]
		public int OrgID
		{
			get{ return _OrgID; }
			set
			{
				this.OnPropertyValueChange("OrgID");
				this._OrgID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ScanTime")]
		public DateTime? ScanTime
		{
			get{ return _ScanTime; }
			set
			{
				this.OnPropertyValueChange("ScanTime");
				this._ScanTime = value;
			}
		}
		/// <summary>
		/// _0-否;1-是
		/// </summary>
		[Field("Status")]
		public int? Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange("Status");
				this._Status = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.Barcode,
				_.SN,
				_.PackSN,
				_.MaterialProNo,
				_.MaterialCode,
				_.OrderType,
				_.OrderNumber,
				_.ResNum,
				_.OptName,
				_.OrgID,
				_.ScanTime,
				_.Status,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._Barcode,
				this._SN,
				this._PackSN,
				this._MaterialProNo,
				this._MaterialCode,
				this._OrderType,
				this._OrderNumber,
				this._ResNum,
				this._OptName,
				this._OrgID,
				this._ScanTime,
				this._Status,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Mes_Tra_OutStock");
            /// <summary>
			/// MappingId
			/// </summary>
			public readonly static Field ID = new Field("ID", "Mes_Tra_OutStock", "MappingId");
            /// <summary>
			/// 员工信息Id
			/// </summary>
			public readonly static Field Barcode = new Field("Barcode", "Mes_Tra_OutStock", "员工信息Id");
            /// <summary>
			/// 角色信息ID
			/// </summary>
			public readonly static Field SN = new Field("SN", "Mes_Tra_OutStock", "角色信息ID");
            /// <summary>
			/// 外箱SN生成原则(YYYYMMDDHHMMSSS)
			/// </summary>
			public readonly static Field PackSN = new Field("PackSN", "Mes_Tra_OutStock", "外箱SN生成原则(YYYYMMDDHHMMSSS)");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialProNo = new Field("MaterialProNo", "Mes_Tra_OutStock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "Mes_Tra_OutStock", "");
            /// <summary>
			/// 订单单别
			/// </summary>
			public readonly static Field OrderType = new Field("OrderType", "Mes_Tra_OutStock", "订单单别");
            /// <summary>
			/// 订单单号
			/// </summary>
			public readonly static Field OrderNumber = new Field("OrderNumber", "Mes_Tra_OutStock", "订单单号");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ResNum = new Field("ResNum", "Mes_Tra_OutStock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OptName = new Field("OptName", "Mes_Tra_OutStock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OrgID = new Field("OrgID", "Mes_Tra_OutStock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ScanTime = new Field("ScanTime", "Mes_Tra_OutStock", "");
            /// <summary>
			/// _0-否;1-是
			/// </summary>
			public readonly static Field Status = new Field("Status", "Mes_Tra_OutStock", "_0-否;1-是");
        }
        #endregion
	}
}