//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Stock_OutMaterial。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Stock_OutMaterial")]
    [Serializable]
    public partial class Mes_Stock_OutMaterial : Entity
    {
        #region Model
        private int _ID;
        private string _BillType;
        private string _BillNo;
        private DateTime _OutStockDate;
        private string _OptPerson;
        private int _OrgID;
        private DateTime? _BillDate;
        private int _AuditStatus;
        private int _TotalNum;
        private string _Memo;
        private string _Creater;
        private DateTime _CreatedTime;
        private string _Modifier;
        private DateTime? _ModifiedTime;
        private string _OrgName;
        private string _Factory;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// LL01-领料单;LL02-异常领料单
        /// </summary>
        [Field("BillType")]
        public string BillType
        {
            get { return _BillType; }
            set
            {
                this.OnPropertyValueChange("BillType");
                this._BillType = value;
            }
        }
        /// <summary>
        /// 领料单号
        /// </summary>
        [Field("BillNo")]
        public string BillNo
        {
            get { return _BillNo; }
            set
            {
                this.OnPropertyValueChange("BillNo");
                this._BillNo = value;
            }
        }
        /// <summary>
        /// 领料日期
        /// </summary>
        [Field("OutStockDate")]
        public DateTime OutStockDate
        {
            get { return _OutStockDate; }
            set
            {
                this.OnPropertyValueChange("OutStockDate");
                this._OutStockDate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("OptPerson")]
        public string OptPerson
        {
            get { return _OptPerson; }
            set
            {
                this.OnPropertyValueChange("OptPerson");
                this._OptPerson = value;
            }
        }
        /// <summary>
        /// 班组ID
        /// </summary>
        [Field("OrgID")]
        public int OrgID
        {
            get { return _OrgID; }
            set
            {
                this.OnPropertyValueChange("OrgID");
                this._OrgID = value;
            }
        }
        /// <summary>
        /// 单据日期
        /// </summary>
        [Field("BillDate")]
        public DateTime? BillDate
        {
            get { return _BillDate; }
            set
            {
                this.OnPropertyValueChange("BillDate");
                this._BillDate = value;
            }
        }
        /// <summary>
        /// _1-未审核;2-已审核
        /// </summary>
        [Field("AuditStatus")]
        public int AuditStatus
        {
            get { return _AuditStatus; }
            set
            {
                this.OnPropertyValueChange("AuditStatus");
                this._AuditStatus = value;
            }
        }
        /// <summary>
        /// 领料数量
        /// </summary>
        [Field("TotalNum")]
        public int TotalNum
        {
            get { return _TotalNum; }
            set
            {
                this.OnPropertyValueChange("TotalNum");
                this._TotalNum = value;
            }
        }
        /// <summary>
        /// 备注
        /// </summary>
        [Field("Memo")]
        public string Memo
        {
            get { return _Memo; }
            set
            {
                this.OnPropertyValueChange("Memo");
                this._Memo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Creater")]
        public string Creater
        {
            get { return _Creater; }
            set
            {
                this.OnPropertyValueChange("Creater");
                this._Creater = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreatedTime")]
        public DateTime CreatedTime
        {
            get { return _CreatedTime; }
            set
            {
                this.OnPropertyValueChange("CreatedTime");
                this._CreatedTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Modifier")]
        public string Modifier
        {
            get { return _Modifier; }
            set
            {
                this.OnPropertyValueChange("Modifier");
                this._Modifier = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ModifiedTime")]
        public DateTime? ModifiedTime
        {
            get { return _ModifiedTime; }
            set
            {
                this.OnPropertyValueChange("ModifiedTime");
                this._ModifiedTime = value;
            }
        }
        /// <summary>
        /// 班组
        /// </summary>
        [Field("OrgName")]
        public string OrgName
        {
            get { return _OrgName; }
            set
            {
                this.OnPropertyValueChange("OrgName");
                this._OrgName = value;
            }
        }
        /// <summary>
        /// 工厂
        /// </summary>
        [Field("Factory")]
        public string Factory
        {
            get { return _Factory; }
            set
            {
                this.OnPropertyValueChange("Factory");
                this._Factory = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
				_.BillType,
				_.BillNo,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.BillType,
				_.BillNo,
				_.OutStockDate,
				_.OptPerson,
				_.OrgID,
				_.BillDate,
				_.AuditStatus,
				_.TotalNum,
				_.Memo,
				_.Creater,
				_.CreatedTime,
				_.Modifier,
				_.ModifiedTime,
				_.OrgName,
				_.Factory,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._BillType,
				this._BillNo,
				this._OutStockDate,
				this._OptPerson,
				this._OrgID,
				this._BillDate,
				this._AuditStatus,
				this._TotalNum,
				this._Memo,
				this._Creater,
				this._CreatedTime,
				this._Modifier,
				this._ModifiedTime,
				this._OrgName,
				this._Factory,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Mes_Stock_OutMaterial");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ID = new Field("ID", "Mes_Stock_OutMaterial", "");
            /// <summary>
            /// LL01-领料单;LL02-异常领料单
            /// </summary>
            public readonly static Field BillType = new Field("BillType", "Mes_Stock_OutMaterial", "LL01-领料单;LL02-异常领料单");
            /// <summary>
            /// 领料单号
            /// </summary>
            public readonly static Field BillNo = new Field("BillNo", "Mes_Stock_OutMaterial", "领料单号");
            /// <summary>
            /// 领料日期
            /// </summary>
            public readonly static Field OutStockDate = new Field("OutStockDate", "Mes_Stock_OutMaterial", "领料日期");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OptPerson = new Field("OptPerson", "Mes_Stock_OutMaterial", "");
            /// <summary>
            /// 班组ID
            /// </summary>
            public readonly static Field OrgID = new Field("OrgID", "Mes_Stock_OutMaterial", "班组ID");
            /// <summary>
            /// 单据日期
            /// </summary>
            public readonly static Field BillDate = new Field("BillDate", "Mes_Stock_OutMaterial", "单据日期");
            /// <summary>
            /// _1-未审核;2-已审核
            /// </summary>
            public readonly static Field AuditStatus = new Field("AuditStatus", "Mes_Stock_OutMaterial", "_1-未审核;2-已审核");
            /// <summary>
            /// 领料数量
            /// </summary>
            public readonly static Field TotalNum = new Field("TotalNum", "Mes_Stock_OutMaterial", "领料数量");
            /// <summary>
            /// 备注
            /// </summary>
            public readonly static Field Memo = new Field("Memo", "Mes_Stock_OutMaterial", "备注");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Creater = new Field("Creater", "Mes_Stock_OutMaterial", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Stock_OutMaterial", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Modifier = new Field("Modifier", "Mes_Stock_OutMaterial", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ModifiedTime = new Field("ModifiedTime", "Mes_Stock_OutMaterial", "");
            /// <summary>
            /// 班组
            /// </summary>
            public readonly static Field OrgName = new Field("OrgName", "Mes_Stock_OutMaterial", "班组");
            /// <summary>
            /// 工厂
            /// </summary>
            public readonly static Field Factory = new Field("Factory", "Mes_Stock_OutMaterial", "工厂");
        }
        #endregion
    }
}