//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Plan_WorkOrder。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Plan_WorkOrder")]
    [Serializable]
    public partial class Mes_Plan_WorkOrder : Entity
    {
        #region Model
		private int _ID;
		private string _FactoryCode;
		private string _WorkOrderType;
		private string _WorkOrderNumber;
		private string _PlanCode;
		private string _SaleNo;
		private string _MaterialProNo;
		private string _MaterialCode;
		private string _Version;
		private int _WorkNum;
		private string _Unit;
		private string _WorkShopCode;
		private DateTime? _PlanBeginTime;
		private DateTime? _PlanEndTime;
		private DateTime? _ActuralBeginTime;
		private DateTime? _ActuralEndTime;
		private int _WorkOrderStatus;
		private string _TraceCode;
		private string _Creater;
		private DateTime _CreatedTime;

		/// <summary>
		/// MappingId
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FactoryCode")]
		public string FactoryCode
		{
			get{ return _FactoryCode; }
			set
			{
				this.OnPropertyValueChange("FactoryCode");
				this._FactoryCode = value;
			}
		}
		/// <summary>
		/// 工单类型(WK10-正常工单;WK20-返工工单)
		/// </summary>
		[Field("WorkOrderType")]
		public string WorkOrderType
		{
			get{ return _WorkOrderType; }
			set
			{
				this.OnPropertyValueChange("WorkOrderType");
				this._WorkOrderType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("WorkOrderNumber")]
		public string WorkOrderNumber
		{
			get{ return _WorkOrderNumber; }
			set
			{
				this.OnPropertyValueChange("WorkOrderNumber");
				this._WorkOrderNumber = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PlanCode")]
		public string PlanCode
		{
			get{ return _PlanCode; }
			set
			{
				this.OnPropertyValueChange("PlanCode");
				this._PlanCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SaleNo")]
		public string SaleNo
		{
			get{ return _SaleNo; }
			set
			{
				this.OnPropertyValueChange("SaleNo");
				this._SaleNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialProNo")]
		public string MaterialProNo
		{
			get{ return _MaterialProNo; }
			set
			{
				this.OnPropertyValueChange("MaterialProNo");
				this._MaterialProNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get{ return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Version")]
		public string Version
		{
			get{ return _Version; }
			set
			{
				this.OnPropertyValueChange("Version");
				this._Version = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("WorkNum")]
		public int WorkNum
		{
			get{ return _WorkNum; }
			set
			{
				this.OnPropertyValueChange("WorkNum");
				this._WorkNum = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Unit")]
		public string Unit
		{
			get{ return _Unit; }
			set
			{
				this.OnPropertyValueChange("Unit");
				this._Unit = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("WorkShopCode")]
		public string WorkShopCode
		{
			get{ return _WorkShopCode; }
			set
			{
				this.OnPropertyValueChange("WorkShopCode");
				this._WorkShopCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PlanBeginTime")]
		public DateTime? PlanBeginTime
		{
			get{ return _PlanBeginTime; }
			set
			{
				this.OnPropertyValueChange("PlanBeginTime");
				this._PlanBeginTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PlanEndTime")]
		public DateTime? PlanEndTime
		{
			get{ return _PlanEndTime; }
			set
			{
				this.OnPropertyValueChange("PlanEndTime");
				this._PlanEndTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ActuralBeginTime")]
		public DateTime? ActuralBeginTime
		{
			get{ return _ActuralBeginTime; }
			set
			{
				this.OnPropertyValueChange("ActuralBeginTime");
				this._ActuralBeginTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ActuralEndTime")]
		public DateTime? ActuralEndTime
		{
			get{ return _ActuralEndTime; }
			set
			{
				this.OnPropertyValueChange("ActuralEndTime");
				this._ActuralEndTime = value;
			}
		}
		/// <summary>
		/// _1-释放;2-下达;3-在制;4-完工;5-关闭
		/// </summary>
		[Field("WorkOrderStatus")]
		public int WorkOrderStatus
		{
			get{ return _WorkOrderStatus; }
			set
			{
				this.OnPropertyValueChange("WorkOrderStatus");
				this._WorkOrderStatus = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TraceCode")]
		public string TraceCode
		{
			get{ return _TraceCode; }
			set
			{
				this.OnPropertyValueChange("TraceCode");
				this._TraceCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Creater")]
		public string Creater
		{
			get{ return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedTime")]
		public DateTime CreatedTime
		{
			get{ return _CreatedTime; }
			set
			{
				this.OnPropertyValueChange("CreatedTime");
				this._CreatedTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.FactoryCode,
				_.WorkOrderType,
				_.WorkOrderNumber,
				_.PlanCode,
				_.SaleNo,
				_.MaterialProNo,
				_.MaterialCode,
				_.Version,
				_.WorkNum,
				_.Unit,
				_.WorkShopCode,
				_.PlanBeginTime,
				_.PlanEndTime,
				_.ActuralBeginTime,
				_.ActuralEndTime,
				_.WorkOrderStatus,
				_.TraceCode,
				_.Creater,
				_.CreatedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._FactoryCode,
				this._WorkOrderType,
				this._WorkOrderNumber,
				this._PlanCode,
				this._SaleNo,
				this._MaterialProNo,
				this._MaterialCode,
				this._Version,
				this._WorkNum,
				this._Unit,
				this._WorkShopCode,
				this._PlanBeginTime,
				this._PlanEndTime,
				this._ActuralBeginTime,
				this._ActuralEndTime,
				this._WorkOrderStatus,
				this._TraceCode,
				this._Creater,
				this._CreatedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Mes_Plan_WorkOrder");
            /// <summary>
			/// MappingId
			/// </summary>
			public readonly static Field ID = new Field("ID", "Mes_Plan_WorkOrder", "MappingId");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FactoryCode = new Field("FactoryCode", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 工单类型(WK10-正常工单;WK20-返工工单)
			/// </summary>
			public readonly static Field WorkOrderType = new Field("WorkOrderType", "Mes_Plan_WorkOrder", "工单类型(WK10-正常工单;WK20-返工工单)");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field WorkOrderNumber = new Field("WorkOrderNumber", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PlanCode = new Field("PlanCode", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SaleNo = new Field("SaleNo", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialProNo = new Field("MaterialProNo", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Version = new Field("Version", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field WorkNum = new Field("WorkNum", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Unit = new Field("Unit", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field WorkShopCode = new Field("WorkShopCode", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PlanBeginTime = new Field("PlanBeginTime", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PlanEndTime = new Field("PlanEndTime", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ActuralBeginTime = new Field("ActuralBeginTime", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ActuralEndTime = new Field("ActuralEndTime", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// _1-释放;2-下达;3-在制;4-完工;5-关闭
			/// </summary>
			public readonly static Field WorkOrderStatus = new Field("WorkOrderStatus", "Mes_Plan_WorkOrder", "_1-释放;2-下达;3-在制;4-完工;5-关闭");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TraceCode = new Field("TraceCode", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Creater = new Field("Creater", "Mes_Plan_WorkOrder", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Plan_WorkOrder", "");
        }
        #endregion
	}
}