//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Sys_Employee。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Sys_Employee")]
    [Serializable]
    public partial class Mes_Sys_Employee : Entity
    {
        #region Model
        private int _ID;
        private string _EmpNo;
        private string _EmpName;
        private string _PostCode;
        private int? _OrgID;
        private string _ProcessList;
        private int _RecordStatus;
        private string _Creater;
        private DateTime? _CreatedTime;
        private string _Modifier;
        private DateTime? _ModifiedTime;
        private string _ProcessNameList;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 员工编号
        /// </summary>
        [Field("EmpNo")]
        public string EmpNo
        {
            get { return _EmpNo; }
            set
            {
                this.OnPropertyValueChange("EmpNo");
                this._EmpNo = value;
            }
        }
        /// <summary>
        /// 员工姓名
        /// </summary>
        [Field("EmpName")]
        public string EmpName
        {
            get { return _EmpName; }
            set
            {
                this.OnPropertyValueChange("EmpName");
                this._EmpName = value;
            }
        }
        /// <summary>
        /// 岗位编码
        /// </summary>
        [Field("PostCode")]
        public string PostCode
        {
            get { return _PostCode; }
            set
            {
                this.OnPropertyValueChange("PostCode");
                this._PostCode = value;
            }
        }
        /// <summary>
        /// 部门ID
        /// </summary>
        [Field("OrgID")]
        public int? OrgID
        {
            get { return _OrgID; }
            set
            {
                this.OnPropertyValueChange("OrgID");
                this._OrgID = value;
            }
        }
        /// <summary>
        /// 工序列表
        /// </summary>
        [Field("ProcessList")]
        public string ProcessList
        {
            get { return _ProcessList; }
            set
            {
                this.OnPropertyValueChange("ProcessList");
                this._ProcessList = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("RecordStatus")]
        public int RecordStatus
        {
            get { return _RecordStatus; }
            set
            {
                this.OnPropertyValueChange("RecordStatus");
                this._RecordStatus = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Creater")]
        public string Creater
        {
            get { return _Creater; }
            set
            {
                this.OnPropertyValueChange("Creater");
                this._Creater = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreatedTime")]
        public DateTime? CreatedTime
        {
            get { return _CreatedTime; }
            set
            {
                this.OnPropertyValueChange("CreatedTime");
                this._CreatedTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Modifier")]
        public string Modifier
        {
            get { return _Modifier; }
            set
            {
                this.OnPropertyValueChange("Modifier");
                this._Modifier = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ModifiedTime")]
        public DateTime? ModifiedTime
        {
            get { return _ModifiedTime; }
            set
            {
                this.OnPropertyValueChange("ModifiedTime");
                this._ModifiedTime = value;
            }
        }
        /// <summary>
        /// 工序名称列表
        /// </summary>
        [Field("ProcessNameList")]
        public string ProcessNameList
        {
            get { return _ProcessNameList; }
            set
            {
                this.OnPropertyValueChange("ProcessNameList");
                this._ProcessNameList = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
				_.EmpNo,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.EmpNo,
				_.EmpName,
				_.PostCode,
				_.OrgID,
				_.ProcessList,
				_.RecordStatus,
				_.Creater,
				_.CreatedTime,
				_.Modifier,
				_.ModifiedTime,
				_.ProcessNameList,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._EmpNo,
				this._EmpName,
				this._PostCode,
				this._OrgID,
				this._ProcessList,
				this._RecordStatus,
				this._Creater,
				this._CreatedTime,
				this._Modifier,
				this._ModifiedTime,
				this._ProcessNameList,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Mes_Sys_Employee");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ID = new Field("ID", "Mes_Sys_Employee", "");
            /// <summary>
            /// 员工编号
            /// </summary>
            public readonly static Field EmpNo = new Field("EmpNo", "Mes_Sys_Employee", "员工编号");
            /// <summary>
            /// 员工姓名
            /// </summary>
            public readonly static Field EmpName = new Field("EmpName", "Mes_Sys_Employee", "员工姓名");
            /// <summary>
            /// 岗位编码
            /// </summary>
            public readonly static Field PostCode = new Field("PostCode", "Mes_Sys_Employee", "岗位编码");
            /// <summary>
            /// 部门ID
            /// </summary>
            public readonly static Field OrgID = new Field("OrgID", "Mes_Sys_Employee", "部门ID");
            /// <summary>
            /// 工序列表
            /// </summary>
            public readonly static Field ProcessList = new Field("ProcessList", "Mes_Sys_Employee", "工序列表");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RecordStatus = new Field("RecordStatus", "Mes_Sys_Employee", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Creater = new Field("Creater", "Mes_Sys_Employee", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Sys_Employee", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Modifier = new Field("Modifier", "Mes_Sys_Employee", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ModifiedTime = new Field("ModifiedTime", "Mes_Sys_Employee", "");
            /// <summary>
            /// 工序名称列表
            /// </summary>
            public readonly static Field ProcessNameList = new Field("ProcessNameList", "Mes_Sys_Employee", "工序名称列表");
        }
        #endregion
    }
}