//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Sys_Customer。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Sys_Customer")]
    [Serializable]
    public partial class Mes_Sys_Customer : Entity
    {
        #region Model
		private int _ID;
		private string _CustomerCode;
		private string _CustomerName;
		private string _Phone;
		private string _Contacter;
		private string _Address;
		private string _PostCode;
		private string _Memo;
		private string _Creater;
		private DateTime? _CreatedTime;
		private string _Modifier;
		private DateTime? _ModifiedTime;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CustomerCode")]
		public string CustomerCode
		{
			get{ return _CustomerCode; }
			set
			{
				this.OnPropertyValueChange("CustomerCode");
				this._CustomerCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CustomerName")]
		public string CustomerName
		{
			get{ return _CustomerName; }
			set
			{
				this.OnPropertyValueChange("CustomerName");
				this._CustomerName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Phone")]
		public string Phone
		{
			get{ return _Phone; }
			set
			{
				this.OnPropertyValueChange("Phone");
				this._Phone = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Contacter")]
		public string Contacter
		{
			get{ return _Contacter; }
			set
			{
				this.OnPropertyValueChange("Contacter");
				this._Contacter = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Address")]
		public string Address
		{
			get{ return _Address; }
			set
			{
				this.OnPropertyValueChange("Address");
				this._Address = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PostCode")]
		public string PostCode
		{
			get{ return _PostCode; }
			set
			{
				this.OnPropertyValueChange("PostCode");
				this._PostCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Memo")]
		public string Memo
		{
			get{ return _Memo; }
			set
			{
				this.OnPropertyValueChange("Memo");
				this._Memo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Creater")]
		public string Creater
		{
			get{ return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedTime")]
		public DateTime? CreatedTime
		{
			get{ return _CreatedTime; }
			set
			{
				this.OnPropertyValueChange("CreatedTime");
				this._CreatedTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Modifier")]
		public string Modifier
		{
			get{ return _Modifier; }
			set
			{
				this.OnPropertyValueChange("Modifier");
				this._Modifier = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ModifiedTime")]
		public DateTime? ModifiedTime
		{
			get{ return _ModifiedTime; }
			set
			{
				this.OnPropertyValueChange("ModifiedTime");
				this._ModifiedTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.CustomerCode,
				_.CustomerName,
				_.Phone,
				_.Contacter,
				_.Address,
				_.PostCode,
				_.Memo,
				_.Creater,
				_.CreatedTime,
				_.Modifier,
				_.ModifiedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._CustomerCode,
				this._CustomerName,
				this._Phone,
				this._Contacter,
				this._Address,
				this._PostCode,
				this._Memo,
				this._Creater,
				this._CreatedTime,
				this._Modifier,
				this._ModifiedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Mes_Sys_Customer");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Mes_Sys_Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CustomerCode = new Field("CustomerCode", "Mes_Sys_Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CustomerName = new Field("CustomerName", "Mes_Sys_Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Phone = new Field("Phone", "Mes_Sys_Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Contacter = new Field("Contacter", "Mes_Sys_Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Address = new Field("Address", "Mes_Sys_Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PostCode = new Field("PostCode", "Mes_Sys_Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Memo = new Field("Memo", "Mes_Sys_Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Creater = new Field("Creater", "Mes_Sys_Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Sys_Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Modifier = new Field("Modifier", "Mes_Sys_Customer", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ModifiedTime = new Field("ModifiedTime", "Mes_Sys_Customer", "");
        }
        #endregion
	}
}