//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Sys_FlowConfig。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Sys_FlowConfig")]
    [Serializable]
    public partial class Mes_Sys_FlowConfig : Entity
    {
        #region Model
        private int _ID;
        private string _BusinessType;
        private int? _OptUserID;
        private string _OptUserName;
        private int? _SortNo;
        private string _Creater;
        private DateTime _CreatedTime;

        /// <summary>
        /// 主键
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 业务类型
        /// </summary>
        [Field("BusinessType")]
        public string BusinessType
        {
            get { return _BusinessType; }
            set
            {
                this.OnPropertyValueChange("BusinessType");
                this._BusinessType = value;
            }
        }
        /// <summary>
        /// 操作人员ID
        /// </summary>
        [Field("OptUserID")]
        public int? OptUserID
        {
            get { return _OptUserID; }
            set
            {
                this.OnPropertyValueChange("OptUserID");
                this._OptUserID = value;
            }
        }
        /// <summary>
        /// 操作人员
        /// </summary>
        [Field("OptUserName")]
        public string OptUserName
        {
            get { return _OptUserName; }
            set
            {
                this.OnPropertyValueChange("OptUserName");
                this._OptUserName = value;
            }
        }
        /// <summary>
        /// 排序
        /// </summary>
        [Field("SortNo")]
        public int? SortNo
        {
            get { return _SortNo; }
            set
            {
                this.OnPropertyValueChange("SortNo");
                this._SortNo = value;
            }
        }
        /// <summary>
        /// 创建人
        /// </summary>
        [Field("Creater")]
        public string Creater
        {
            get { return _Creater; }
            set
            {
                this.OnPropertyValueChange("Creater");
                this._Creater = value;
            }
        }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Field("CreatedTime")]
        public DateTime CreatedTime
        {
            get { return _CreatedTime; }
            set
            {
                this.OnPropertyValueChange("CreatedTime");
                this._CreatedTime = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.BusinessType,
				_.OptUserID,
				_.OptUserName,
				_.SortNo,
				_.Creater,
				_.CreatedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._BusinessType,
				this._OptUserID,
				this._OptUserName,
				this._SortNo,
				this._Creater,
				this._CreatedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Mes_Sys_FlowConfig");
            /// <summary>
            /// 主键
            /// </summary>
            public readonly static Field ID = new Field("ID", "Mes_Sys_FlowConfig", "主键");
            /// <summary>
            /// 业务类型
            /// </summary>
            public readonly static Field BusinessType = new Field("BusinessType", "Mes_Sys_FlowConfig", "业务类型");
            /// <summary>
            /// 操作人员ID
            /// </summary>
            public readonly static Field OptUserID = new Field("OptUserID", "Mes_Sys_FlowConfig", "操作人员ID");
            /// <summary>
            /// 操作人员
            /// </summary>
            public readonly static Field OptUserName = new Field("OptUserName", "Mes_Sys_FlowConfig", "操作人员");
            /// <summary>
            /// 排序
            /// </summary>
            public readonly static Field SortNo = new Field("SortNo", "Mes_Sys_FlowConfig", "排序");
            /// <summary>
            /// 创建人
            /// </summary>
            public readonly static Field Creater = new Field("Creater", "Mes_Sys_FlowConfig", "创建人");
            /// <summary>
            /// 创建时间
            /// </summary>
            public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Sys_FlowConfig", "创建时间");
        }
        #endregion
    }
}