//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Stock_OutMaterialItem。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Stock_OutMaterialItem")]
    [Serializable]
    public partial class Mes_Stock_OutMaterialItem : Entity
    {
        #region Model
        private int _ID;
        private string _BillType;
        private string _BillNo;
        private int _ResNum;
        private string _MaterialProNo;
        private string _MaterialCode;
        private string _MaterialSize;
        private int _Num;
        private string _Unit;
        private string _BatchNo;
        private string _WorkOrderType;
        private string _PlanNo;
        private string _Memo;
        private string _Creater;
        private DateTime _CreatedTime;
        private string _Modifier;
        private DateTime? _ModifiedTime;
        private int? _OutMaterialID;
        private int? _StockID;
        private string _StockName;
        private int? _AlibraryID;
        private string _AlibraryName;
        private int? _ProcessID;
        private string _ProcessName;
        private string _Version;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// LL01-领料单;LL02-异常领料单
        /// </summary>
        [Field("BillType")]
        public string BillType
        {
            get { return _BillType; }
            set
            {
                this.OnPropertyValueChange("BillType");
                this._BillType = value;
            }
        }
        /// <summary>
        /// 领料单号
        /// </summary>
        [Field("BillNo")]
        public string BillNo
        {
            get { return _BillNo; }
            set
            {
                this.OnPropertyValueChange("BillNo");
                this._BillNo = value;
            }
        }
        /// <summary>
        /// 行号
        /// </summary>
        [Field("ResNum")]
        public int ResNum
        {
            get { return _ResNum; }
            set
            {
                this.OnPropertyValueChange("ResNum");
                this._ResNum = value;
            }
        }
        /// <summary>
        /// 产品编码
        /// </summary>
        [Field("MaterialProNo")]
        public string MaterialProNo
        {
            get { return _MaterialProNo; }
            set
            {
                this.OnPropertyValueChange("MaterialProNo");
                this._MaterialProNo = value;
            }
        }
        /// <summary>
        /// 产品简称
        /// </summary>
        [Field("MaterialCode")]
        public string MaterialCode
        {
            get { return _MaterialCode; }
            set
            {
                this.OnPropertyValueChange("MaterialCode");
                this._MaterialCode = value;
            }
        }
        /// <summary>
        /// 产品规格
        /// </summary>
        [Field("MaterialSize")]
        public string MaterialSize
        {
            get { return _MaterialSize; }
            set
            {
                this.OnPropertyValueChange("MaterialSize");
                this._MaterialSize = value;
            }
        }
        /// <summary>
        /// 数量
        /// </summary>
        [Field("Num")]
        public int Num
        {
            get { return _Num; }
            set
            {
                this.OnPropertyValueChange("Num");
                this._Num = value;
            }
        }
        /// <summary>
        /// 单位
        /// </summary>
        [Field("Unit")]
        public string Unit
        {
            get { return _Unit; }
            set
            {
                this.OnPropertyValueChange("Unit");
                this._Unit = value;
            }
        }
        /// <summary>
        /// 批次号(进货单批次号关联)
        /// </summary>
        [Field("BatchNo")]
        public string BatchNo
        {
            get { return _BatchNo; }
            set
            {
                this.OnPropertyValueChange("BatchNo");
                this._BatchNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("WorkOrderType")]
        public string WorkOrderType
        {
            get { return _WorkOrderType; }
            set
            {
                this.OnPropertyValueChange("WorkOrderType");
                this._WorkOrderType = value;
            }
        }
        /// <summary>
        /// 计划批号
        /// </summary>
        [Field("PlanNo")]
        public string PlanNo
        {
            get { return _PlanNo; }
            set
            {
                this.OnPropertyValueChange("PlanNo");
                this._PlanNo = value;
            }
        }
        /// <summary>
        /// 备注
        /// </summary>
        [Field("Memo")]
        public string Memo
        {
            get { return _Memo; }
            set
            {
                this.OnPropertyValueChange("Memo");
                this._Memo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Creater")]
        public string Creater
        {
            get { return _Creater; }
            set
            {
                this.OnPropertyValueChange("Creater");
                this._Creater = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreatedTime")]
        public DateTime CreatedTime
        {
            get { return _CreatedTime; }
            set
            {
                this.OnPropertyValueChange("CreatedTime");
                this._CreatedTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Modifier")]
        public string Modifier
        {
            get { return _Modifier; }
            set
            {
                this.OnPropertyValueChange("Modifier");
                this._Modifier = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ModifiedTime")]
        public DateTime? ModifiedTime
        {
            get { return _ModifiedTime; }
            set
            {
                this.OnPropertyValueChange("ModifiedTime");
                this._ModifiedTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("OutMaterialID")]
        public int? OutMaterialID
        {
            get { return _OutMaterialID; }
            set
            {
                this.OnPropertyValueChange("OutMaterialID");
                this._OutMaterialID = value;
            }
        }
        /// <summary>
        /// 仓库ID
        /// </summary>
        [Field("StockID")]
        public int? StockID
        {
            get { return _StockID; }
            set
            {
                this.OnPropertyValueChange("StockID");
                this._StockID = value;
            }
        }
        /// <summary>
        /// 仓库
        /// </summary>
        [Field("StockName")]
        public string StockName
        {
            get { return _StockName; }
            set
            {
                this.OnPropertyValueChange("StockName");
                this._StockName = value;
            }
        }
        /// <summary>
        /// 库位ID
        /// </summary>
        [Field("AlibraryID")]
        public int? AlibraryID
        {
            get { return _AlibraryID; }
            set
            {
                this.OnPropertyValueChange("AlibraryID");
                this._AlibraryID = value;
            }
        }
        /// <summary>
        /// 库位
        /// </summary>
        [Field("AlibraryName")]
        public string AlibraryName
        {
            get { return _AlibraryName; }
            set
            {
                this.OnPropertyValueChange("AlibraryName");
                this._AlibraryName = value;
            }
        }
        /// <summary>
        /// 工序ID
        /// </summary>
        [Field("ProcessID")]
        public int? ProcessID
        {
            get { return _ProcessID; }
            set
            {
                this.OnPropertyValueChange("ProcessID");
                this._ProcessID = value;
            }
        }
        /// <summary>
        /// 工序
        /// </summary>
        [Field("ProcessName")]
        public string ProcessName
        {
            get { return _ProcessName; }
            set
            {
                this.OnPropertyValueChange("ProcessName");
                this._ProcessName = value;
            }
        }
        /// <summary>
        /// 版本
        /// </summary>
        [Field("Version")]
        public string Version
        {
            get { return _Version; }
            set
            {
                this.OnPropertyValueChange("Version");
                this._Version = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
				_.BillType,
				_.BillNo,
				_.ResNum,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.BillType,
				_.BillNo,
				_.ResNum,
				_.MaterialProNo,
				_.MaterialCode,
				_.MaterialSize,
				_.Num,
				_.Unit,
				_.BatchNo,
				_.WorkOrderType,
				_.PlanNo,
				_.Memo,
				_.Creater,
				_.CreatedTime,
				_.Modifier,
				_.ModifiedTime,
				_.OutMaterialID,
				_.StockID,
				_.StockName,
				_.AlibraryID,
				_.AlibraryName,
				_.ProcessID,
				_.ProcessName,
				_.Version,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._BillType,
				this._BillNo,
				this._ResNum,
				this._MaterialProNo,
				this._MaterialCode,
				this._MaterialSize,
				this._Num,
				this._Unit,
				this._BatchNo,
				this._WorkOrderType,
				this._PlanNo,
				this._Memo,
				this._Creater,
				this._CreatedTime,
				this._Modifier,
				this._ModifiedTime,
				this._OutMaterialID,
				this._StockID,
				this._StockName,
				this._AlibraryID,
				this._AlibraryName,
				this._ProcessID,
				this._ProcessName,
				this._Version,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Mes_Stock_OutMaterialItem");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ID = new Field("ID", "Mes_Stock_OutMaterialItem", "");
            /// <summary>
            /// LL01-领料单;LL02-异常领料单
            /// </summary>
            public readonly static Field BillType = new Field("BillType", "Mes_Stock_OutMaterialItem", "LL01-领料单;LL02-异常领料单");
            /// <summary>
            /// 领料单号
            /// </summary>
            public readonly static Field BillNo = new Field("BillNo", "Mes_Stock_OutMaterialItem", "领料单号");
            /// <summary>
            /// 行号
            /// </summary>
            public readonly static Field ResNum = new Field("ResNum", "Mes_Stock_OutMaterialItem", "行号");
            /// <summary>
            /// 产品编码
            /// </summary>
            public readonly static Field MaterialProNo = new Field("MaterialProNo", "Mes_Stock_OutMaterialItem", "产品编码");
            /// <summary>
            /// 产品简称
            /// </summary>
            public readonly static Field MaterialCode = new Field("MaterialCode", "Mes_Stock_OutMaterialItem", "产品简称");
            /// <summary>
            /// 产品规格
            /// </summary>
            public readonly static Field MaterialSize = new Field("MaterialSize", "Mes_Stock_OutMaterialItem", "产品规格");
            /// <summary>
            /// 数量
            /// </summary>
            public readonly static Field Num = new Field("Num", "Mes_Stock_OutMaterialItem", "数量");
            /// <summary>
            /// 单位
            /// </summary>
            public readonly static Field Unit = new Field("Unit", "Mes_Stock_OutMaterialItem", "单位");
            /// <summary>
            /// 批次号(进货单批次号关联)
            /// </summary>
            public readonly static Field BatchNo = new Field("BatchNo", "Mes_Stock_OutMaterialItem", "批次号(进货单批次号关联)");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field WorkOrderType = new Field("WorkOrderType", "Mes_Stock_OutMaterialItem", "");
            /// <summary>
            /// 计划批号
            /// </summary>
            public readonly static Field PlanNo = new Field("PlanNo", "Mes_Stock_OutMaterialItem", "计划批号");
            /// <summary>
            /// 备注
            /// </summary>
            public readonly static Field Memo = new Field("Memo", "Mes_Stock_OutMaterialItem", "备注");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Creater = new Field("Creater", "Mes_Stock_OutMaterialItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Stock_OutMaterialItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Modifier = new Field("Modifier", "Mes_Stock_OutMaterialItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ModifiedTime = new Field("ModifiedTime", "Mes_Stock_OutMaterialItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OutMaterialID = new Field("OutMaterialID", "Mes_Stock_OutMaterialItem", "");
            /// <summary>
            /// 仓库ID
            /// </summary>
            public readonly static Field StockID = new Field("StockID", "Mes_Stock_OutMaterialItem", "仓库ID");
            /// <summary>
            /// 仓库
            /// </summary>
            public readonly static Field StockName = new Field("StockName", "Mes_Stock_OutMaterialItem", "仓库");
            /// <summary>
            /// 库位ID
            /// </summary>
            public readonly static Field AlibraryID = new Field("AlibraryID", "Mes_Stock_OutMaterialItem", "库位ID");
            /// <summary>
            /// 库位
            /// </summary>
            public readonly static Field AlibraryName = new Field("AlibraryName", "Mes_Stock_OutMaterialItem", "库位");
            /// <summary>
            /// 工序ID
            /// </summary>
            public readonly static Field ProcessID = new Field("ProcessID", "Mes_Stock_OutMaterialItem", "工序ID");
            /// <summary>
            /// 工序
            /// </summary>
            public readonly static Field ProcessName = new Field("ProcessName", "Mes_Stock_OutMaterialItem", "工序");
            /// <summary>
            /// 版本
            /// </summary>
            public readonly static Field Version = new Field("Version", "Mes_Stock_OutMaterialItem", "版本");
        }
        #endregion
    }
}