//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Stock_InStockApproval。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Stock_InStockApproval")]
    [Serializable]
    public partial class Mes_Stock_InStockApproval : Entity
    {
        #region Model
        private int _ID;
        private string _BillNo;
        private string _BillType;
        private int? _ApproverID;
        private string _ApproverName;
        private string _Memo;
        private int? _ApprovalStatus;
        private string _Creater;
        private DateTime _CreatedTime;

        /// <summary>
        /// 主键
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 进货单号
        /// </summary>
        [Field("BillNo")]
        public string BillNo
        {
            get { return _BillNo; }
            set
            {
                this.OnPropertyValueChange("BillNo");
                this._BillNo = value;
            }
        }
        /// <summary>
        /// 进货单别
        /// </summary>
        [Field("BillType")]
        public string BillType
        {
            get { return _BillType; }
            set
            {
                this.OnPropertyValueChange("BillType");
                this._BillType = value;
            }
        }
        /// <summary>
        /// 审核人ID
        /// </summary>
        [Field("ApproverID")]
        public int? ApproverID
        {
            get { return _ApproverID; }
            set
            {
                this.OnPropertyValueChange("ApproverID");
                this._ApproverID = value;
            }
        }
        /// <summary>
        /// 审核人
        /// </summary>
        [Field("ApproverName")]
        public string ApproverName
        {
            get { return _ApproverName; }
            set
            {
                this.OnPropertyValueChange("ApproverName");
                this._ApproverName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Memo")]
        public string Memo
        {
            get { return _Memo; }
            set
            {
                this.OnPropertyValueChange("Memo");
                this._Memo = value;
            }
        }
        /// <summary>
        /// 审核状态(1:通过 2:不通过)
        /// </summary>
        [Field("ApprovalStatus")]
        public int? ApprovalStatus
        {
            get { return _ApprovalStatus; }
            set
            {
                this.OnPropertyValueChange("ApprovalStatus");
                this._ApprovalStatus = value;
            }
        }
        /// <summary>
        /// 创建人
        /// </summary>
        [Field("Creater")]
        public string Creater
        {
            get { return _Creater; }
            set
            {
                this.OnPropertyValueChange("Creater");
                this._Creater = value;
            }
        }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Field("CreatedTime")]
        public DateTime CreatedTime
        {
            get { return _CreatedTime; }
            set
            {
                this.OnPropertyValueChange("CreatedTime");
                this._CreatedTime = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.BillNo,
				_.BillType,
				_.ApproverID,
				_.ApproverName,
				_.Memo,
				_.ApprovalStatus,
				_.Creater,
				_.CreatedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._BillNo,
				this._BillType,
				this._ApproverID,
				this._ApproverName,
				this._Memo,
				this._ApprovalStatus,
				this._Creater,
				this._CreatedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Mes_Stock_InStockApproval");
            /// <summary>
            /// 主键
            /// </summary>
            public readonly static Field ID = new Field("ID", "Mes_Stock_InStockApproval", "主键");
            /// <summary>
            /// 进货单号
            /// </summary>
            public readonly static Field BillNo = new Field("BillNo", "Mes_Stock_InStockApproval", "进货单号");
            /// <summary>
            /// 进货单别
            /// </summary>
            public readonly static Field BillType = new Field("BillType", "Mes_Stock_InStockApproval", "进货单别");
            /// <summary>
            /// 审核人ID
            /// </summary>
            public readonly static Field ApproverID = new Field("ApproverID", "Mes_Stock_InStockApproval", "审核人ID");
            /// <summary>
            /// 审核人
            /// </summary>
            public readonly static Field ApproverName = new Field("ApproverName", "Mes_Stock_InStockApproval", "审核人");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Memo = new Field("Memo", "Mes_Stock_InStockApproval", "");
            /// <summary>
            /// 审核状态(1:通过 2:不通过)
            /// </summary>
            public readonly static Field ApprovalStatus = new Field("ApprovalStatus", "Mes_Stock_InStockApproval", "审核状态(1:通过 2:不通过)");
            /// <summary>
            /// 创建人
            /// </summary>
            public readonly static Field Creater = new Field("Creater", "Mes_Stock_InStockApproval", "创建人");
            /// <summary>
            /// 创建时间
            /// </summary>
            public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Stock_InStockApproval", "创建时间");
        }
        #endregion
    }
}