//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Tec_TestDataPosition。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Tec_TestDataPosition")]
    [Serializable]
    public partial class Mes_Tec_TestDataPosition : Entity
    {
        #region Model
		private int _ID;
		private string _ProcessCode;
		private string _DataTableName;
		private string _DataProcessName;
		private int? _TestProperty;
		private string _Creater;
		private DateTime? _CreatedTime;
		private string _Modifier;
		private DateTime? _ModifiedTime;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ProcessCode")]
		public string ProcessCode
		{
			get{ return _ProcessCode; }
			set
			{
				this.OnPropertyValueChange("ProcessCode");
				this._ProcessCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DataTableName")]
		public string DataTableName
		{
			get{ return _DataTableName; }
			set
			{
				this.OnPropertyValueChange("DataTableName");
				this._DataTableName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DataProcessName")]
		public string DataProcessName
		{
			get{ return _DataProcessName; }
			set
			{
				this.OnPropertyValueChange("DataProcessName");
				this._DataProcessName = value;
			}
		}
		/// <summary>
		/// _0-合格数据;1-有数据
		/// </summary>
		[Field("TestProperty")]
		public int? TestProperty
		{
			get{ return _TestProperty; }
			set
			{
				this.OnPropertyValueChange("TestProperty");
				this._TestProperty = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Creater")]
		public string Creater
		{
			get{ return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedTime")]
		public DateTime? CreatedTime
		{
			get{ return _CreatedTime; }
			set
			{
				this.OnPropertyValueChange("CreatedTime");
				this._CreatedTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Modifier")]
		public string Modifier
		{
			get{ return _Modifier; }
			set
			{
				this.OnPropertyValueChange("Modifier");
				this._Modifier = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ModifiedTime")]
		public DateTime? ModifiedTime
		{
			get{ return _ModifiedTime; }
			set
			{
				this.OnPropertyValueChange("ModifiedTime");
				this._ModifiedTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.ProcessCode,
				_.DataTableName,
				_.DataProcessName,
				_.TestProperty,
				_.Creater,
				_.CreatedTime,
				_.Modifier,
				_.ModifiedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._ProcessCode,
				this._DataTableName,
				this._DataProcessName,
				this._TestProperty,
				this._Creater,
				this._CreatedTime,
				this._Modifier,
				this._ModifiedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Mes_Tec_TestDataPosition");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Mes_Tec_TestDataPosition", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProcessCode = new Field("ProcessCode", "Mes_Tec_TestDataPosition", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DataTableName = new Field("DataTableName", "Mes_Tec_TestDataPosition", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DataProcessName = new Field("DataProcessName", "Mes_Tec_TestDataPosition", "");
            /// <summary>
			/// _0-合格数据;1-有数据
			/// </summary>
			public readonly static Field TestProperty = new Field("TestProperty", "Mes_Tec_TestDataPosition", "_0-合格数据;1-有数据");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Creater = new Field("Creater", "Mes_Tec_TestDataPosition", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Tec_TestDataPosition", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Modifier = new Field("Modifier", "Mes_Tec_TestDataPosition", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ModifiedTime = new Field("ModifiedTime", "Mes_Tec_TestDataPosition", "");
        }
        #endregion
	}
}