//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Plan_SaleOrderItem。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Plan_SaleOrderItem")]
    [Serializable]
    public partial class Mes_Plan_SaleOrderItem : Entity
    {
        #region Model
        private int _ID;
        private string _OrderType;
        private string _OrderNo;
        private int _ResNum;
        private string _MaterialProNo;
        private string _MaterialCode;
        private string _Version;
        private int _Num;
        private DateTime? _ShipDate;
        private int _AlNum;
        private string _Memo;
        private string _Creater;
        private DateTime _CreatedTime;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 订单单别
        /// </summary>
        [Field("OrderType")]
        public string OrderType
        {
            get { return _OrderType; }
            set
            {
                this.OnPropertyValueChange("OrderType");
                this._OrderType = value;
            }
        }
        /// <summary>
        /// 订单单号
        /// </summary>
        [Field("OrderNo")]
        public string OrderNo
        {
            get { return _OrderNo; }
            set
            {
                this.OnPropertyValueChange("OrderNo");
                this._OrderNo = value;
            }
        }
        /// <summary>
        /// 订单行号
        /// </summary>
        [Field("ResNum")]
        public int ResNum
        {
            get { return _ResNum; }
            set
            {
                this.OnPropertyValueChange("ResNum");
                this._ResNum = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MaterialProNo")]
        public string MaterialProNo
        {
            get { return _MaterialProNo; }
            set
            {
                this.OnPropertyValueChange("MaterialProNo");
                this._MaterialProNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MaterialCode")]
        public string MaterialCode
        {
            get { return _MaterialCode; }
            set
            {
                this.OnPropertyValueChange("MaterialCode");
                this._MaterialCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Version")]
        public string Version
        {
            get { return _Version; }
            set
            {
                this.OnPropertyValueChange("Version");
                this._Version = value;
            }
        }
        /// <summary>
        /// 订单数量
        /// </summary>
        [Field("Num")]
        public int Num
        {
            get { return _Num; }
            set
            {
                this.OnPropertyValueChange("Num");
                this._Num = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ShipDate")]
        public DateTime? ShipDate
        {
            get { return _ShipDate; }
            set
            {
                this.OnPropertyValueChange("ShipDate");
                this._ShipDate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AlNum")]
        public int AlNum
        {
            get { return _AlNum; }
            set
            {
                this.OnPropertyValueChange("AlNum");
                this._AlNum = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Memo")]
        public string Memo
        {
            get { return _Memo; }
            set
            {
                this.OnPropertyValueChange("Memo");
                this._Memo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Creater")]
        public string Creater
        {
            get { return _Creater; }
            set
            {
                this.OnPropertyValueChange("Creater");
                this._Creater = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreatedTime")]
        public DateTime CreatedTime
        {
            get { return _CreatedTime; }
            set
            {
                this.OnPropertyValueChange("CreatedTime");
                this._CreatedTime = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
				_.OrderType,
				_.OrderNo,
				_.ResNum,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.OrderType,
				_.OrderNo,
				_.ResNum,
				_.MaterialProNo,
				_.MaterialCode,
				_.Version,
				_.Num,
				_.ShipDate,
				_.AlNum,
				_.Memo,
				_.Creater,
				_.CreatedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._OrderType,
				this._OrderNo,
				this._ResNum,
				this._MaterialProNo,
				this._MaterialCode,
				this._Version,
				this._Num,
				this._ShipDate,
				this._AlNum,
				this._Memo,
				this._Creater,
				this._CreatedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Mes_Plan_SaleOrderItem");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ID = new Field("ID", "Mes_Plan_SaleOrderItem", "");
            /// <summary>
            /// 订单单别
            /// </summary>
            public readonly static Field OrderType = new Field("OrderType", "Mes_Plan_SaleOrderItem", "订单单别");
            /// <summary>
            /// 订单单号
            /// </summary>
            public readonly static Field OrderNo = new Field("OrderNo", "Mes_Plan_SaleOrderItem", "订单单号");
            /// <summary>
            /// 订单行号
            /// </summary>
            public readonly static Field ResNum = new Field("ResNum", "Mes_Plan_SaleOrderItem", "订单行号");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MaterialProNo = new Field("MaterialProNo", "Mes_Plan_SaleOrderItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MaterialCode = new Field("MaterialCode", "Mes_Plan_SaleOrderItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Version = new Field("Version", "Mes_Plan_SaleOrderItem", "");
            /// <summary>
            /// 订单数量
            /// </summary>
            public readonly static Field Num = new Field("Num", "Mes_Plan_SaleOrderItem", "订单数量");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ShipDate = new Field("ShipDate", "Mes_Plan_SaleOrderItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field AlNum = new Field("AlNum", "Mes_Plan_SaleOrderItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Memo = new Field("Memo", "Mes_Plan_SaleOrderItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Creater = new Field("Creater", "Mes_Plan_SaleOrderItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Plan_SaleOrderItem", "");
        }
        #endregion
    }
}