//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Tec_DeviceOutRecord。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Tec_DeviceOutRecord")]
    [Serializable]
    public partial class Mes_Tec_DeviceOutRecord : Entity
    {
        #region Model
		private int _ID;
		private string _DeviceCode;
		private string _Person;
		private int? _OrgID;
		private DateTime? _OutDate;
		private string _Creater;
		private DateTime? _CreatedTime;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeviceCode")]
		public string DeviceCode
		{
			get{ return _DeviceCode; }
			set
			{
				this.OnPropertyValueChange("DeviceCode");
				this._DeviceCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Person")]
		public string Person
		{
			get{ return _Person; }
			set
			{
				this.OnPropertyValueChange("Person");
				this._Person = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OrgID")]
		public int? OrgID
		{
			get{ return _OrgID; }
			set
			{
				this.OnPropertyValueChange("OrgID");
				this._OrgID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OutDate")]
		public DateTime? OutDate
		{
			get{ return _OutDate; }
			set
			{
				this.OnPropertyValueChange("OutDate");
				this._OutDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Creater")]
		public string Creater
		{
			get{ return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedTime")]
		public DateTime? CreatedTime
		{
			get{ return _CreatedTime; }
			set
			{
				this.OnPropertyValueChange("CreatedTime");
				this._CreatedTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.DeviceCode,
				_.Person,
				_.OrgID,
				_.OutDate,
				_.Creater,
				_.CreatedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._DeviceCode,
				this._Person,
				this._OrgID,
				this._OutDate,
				this._Creater,
				this._CreatedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Mes_Tec_DeviceOutRecord");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Mes_Tec_DeviceOutRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeviceCode = new Field("DeviceCode", "Mes_Tec_DeviceOutRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Person = new Field("Person", "Mes_Tec_DeviceOutRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OrgID = new Field("OrgID", "Mes_Tec_DeviceOutRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OutDate = new Field("OutDate", "Mes_Tec_DeviceOutRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Creater = new Field("Creater", "Mes_Tec_DeviceOutRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Tec_DeviceOutRecord", "");
        }
        #endregion
	}
}