//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Tra_DiscardRecord。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Tra_DiscardRecord")]
    [Serializable]
    public partial class Mes_Tra_DiscardRecord : Entity
    {
        #region Model
		private int _ID;
		private string _Barcode;
		private string _SN;
		private string _MaterialProNo;
		private string _MaterialCode;
		private string _PlanCode;
		private string _Creater;
		private int? _OrgID;
		private DateTime? _CreatedTime;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Barcode")]
		public string Barcode
		{
			get{ return _Barcode; }
			set
			{
				this.OnPropertyValueChange("Barcode");
				this._Barcode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SN")]
		public string SN
		{
			get{ return _SN; }
			set
			{
				this.OnPropertyValueChange("SN");
				this._SN = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialProNo")]
		public string MaterialProNo
		{
			get{ return _MaterialProNo; }
			set
			{
				this.OnPropertyValueChange("MaterialProNo");
				this._MaterialProNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get{ return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PlanCode")]
		public string PlanCode
		{
			get{ return _PlanCode; }
			set
			{
				this.OnPropertyValueChange("PlanCode");
				this._PlanCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Creater")]
		public string Creater
		{
			get{ return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OrgID")]
		public int? OrgID
		{
			get{ return _OrgID; }
			set
			{
				this.OnPropertyValueChange("OrgID");
				this._OrgID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedTime")]
		public DateTime? CreatedTime
		{
			get{ return _CreatedTime; }
			set
			{
				this.OnPropertyValueChange("CreatedTime");
				this._CreatedTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.Barcode,
				_.SN,
				_.MaterialProNo,
				_.MaterialCode,
				_.PlanCode,
				_.Creater,
				_.OrgID,
				_.CreatedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._Barcode,
				this._SN,
				this._MaterialProNo,
				this._MaterialCode,
				this._PlanCode,
				this._Creater,
				this._OrgID,
				this._CreatedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Mes_Tra_DiscardRecord");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Mes_Tra_DiscardRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Barcode = new Field("Barcode", "Mes_Tra_DiscardRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SN = new Field("SN", "Mes_Tra_DiscardRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialProNo = new Field("MaterialProNo", "Mes_Tra_DiscardRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "Mes_Tra_DiscardRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PlanCode = new Field("PlanCode", "Mes_Tra_DiscardRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Creater = new Field("Creater", "Mes_Tra_DiscardRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OrgID = new Field("OrgID", "Mes_Tra_DiscardRecord", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Tra_DiscardRecord", "");
        }
        #endregion
	}
}