//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Sys_Alibrary。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Sys_Alibrary")]
    [Serializable]
    public partial class Mes_Sys_Alibrary : Entity
    {
        #region Model
		private int _ID;
		private string _AlibraryCode;
		private string _AlibraryName;
		private string _StockCode;
		private string _AlibraryContain;
		private string _Creater;
		private DateTime _CreatedTime;
		private string _Modifier;
		private DateTime? _ModifiedTime;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AlibraryCode")]
		public string AlibraryCode
		{
			get{ return _AlibraryCode; }
			set
			{
				this.OnPropertyValueChange("AlibraryCode");
				this._AlibraryCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AlibraryName")]
		public string AlibraryName
		{
			get{ return _AlibraryName; }
			set
			{
				this.OnPropertyValueChange("AlibraryName");
				this._AlibraryName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("StockCode")]
		public string StockCode
		{
			get{ return _StockCode; }
			set
			{
				this.OnPropertyValueChange("StockCode");
				this._StockCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AlibraryContain")]
		public string AlibraryContain
		{
			get{ return _AlibraryContain; }
			set
			{
				this.OnPropertyValueChange("AlibraryContain");
				this._AlibraryContain = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Creater")]
		public string Creater
		{
			get{ return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedTime")]
		public DateTime CreatedTime
		{
			get{ return _CreatedTime; }
			set
			{
				this.OnPropertyValueChange("CreatedTime");
				this._CreatedTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Modifier")]
		public string Modifier
		{
			get{ return _Modifier; }
			set
			{
				this.OnPropertyValueChange("Modifier");
				this._Modifier = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ModifiedTime")]
		public DateTime? ModifiedTime
		{
			get{ return _ModifiedTime; }
			set
			{
				this.OnPropertyValueChange("ModifiedTime");
				this._ModifiedTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
				_.AlibraryCode,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.AlibraryCode,
				_.AlibraryName,
				_.StockCode,
				_.AlibraryContain,
				_.Creater,
				_.CreatedTime,
				_.Modifier,
				_.ModifiedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._AlibraryCode,
				this._AlibraryName,
				this._StockCode,
				this._AlibraryContain,
				this._Creater,
				this._CreatedTime,
				this._Modifier,
				this._ModifiedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Mes_Sys_Alibrary");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Mes_Sys_Alibrary", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AlibraryCode = new Field("AlibraryCode", "Mes_Sys_Alibrary", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AlibraryName = new Field("AlibraryName", "Mes_Sys_Alibrary", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StockCode = new Field("StockCode", "Mes_Sys_Alibrary", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AlibraryContain = new Field("AlibraryContain", "Mes_Sys_Alibrary", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Creater = new Field("Creater", "Mes_Sys_Alibrary", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Sys_Alibrary", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Modifier = new Field("Modifier", "Mes_Sys_Alibrary", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ModifiedTime = new Field("ModifiedTime", "Mes_Sys_Alibrary", "");
        }
        #endregion
	}
}