//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Sys_Stock。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Sys_Stock")]
    [Serializable]
    public partial class Mes_Sys_Stock : Entity
    {
        #region Model
		private int _ID;
		private string _StockCode;
		private string _StockName;
		private string _StockAddress;
		private string _FactoryCode;
		private string _Leader;
		private string _TelPhone;
		private string _Memo;
		private string _Creater;
		private DateTime? _CreatedTime;
		private string _Modifier;
		private DateTime? _ModifiedTime;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("StockCode")]
		public string StockCode
		{
			get{ return _StockCode; }
			set
			{
				this.OnPropertyValueChange("StockCode");
				this._StockCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("StockName")]
		public string StockName
		{
			get{ return _StockName; }
			set
			{
				this.OnPropertyValueChange("StockName");
				this._StockName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("StockAddress")]
		public string StockAddress
		{
			get{ return _StockAddress; }
			set
			{
				this.OnPropertyValueChange("StockAddress");
				this._StockAddress = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FactoryCode")]
		public string FactoryCode
		{
			get{ return _FactoryCode; }
			set
			{
				this.OnPropertyValueChange("FactoryCode");
				this._FactoryCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Leader")]
		public string Leader
		{
			get{ return _Leader; }
			set
			{
				this.OnPropertyValueChange("Leader");
				this._Leader = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TelPhone")]
		public string TelPhone
		{
			get{ return _TelPhone; }
			set
			{
				this.OnPropertyValueChange("TelPhone");
				this._TelPhone = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Memo")]
		public string Memo
		{
			get{ return _Memo; }
			set
			{
				this.OnPropertyValueChange("Memo");
				this._Memo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Creater")]
		public string Creater
		{
			get{ return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedTime")]
		public DateTime? CreatedTime
		{
			get{ return _CreatedTime; }
			set
			{
				this.OnPropertyValueChange("CreatedTime");
				this._CreatedTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Modifier")]
		public string Modifier
		{
			get{ return _Modifier; }
			set
			{
				this.OnPropertyValueChange("Modifier");
				this._Modifier = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ModifiedTime")]
		public DateTime? ModifiedTime
		{
			get{ return _ModifiedTime; }
			set
			{
				this.OnPropertyValueChange("ModifiedTime");
				this._ModifiedTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
				_.StockCode,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.StockCode,
				_.StockName,
				_.StockAddress,
				_.FactoryCode,
				_.Leader,
				_.TelPhone,
				_.Memo,
				_.Creater,
				_.CreatedTime,
				_.Modifier,
				_.ModifiedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._StockCode,
				this._StockName,
				this._StockAddress,
				this._FactoryCode,
				this._Leader,
				this._TelPhone,
				this._Memo,
				this._Creater,
				this._CreatedTime,
				this._Modifier,
				this._ModifiedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Mes_Sys_Stock");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Mes_Sys_Stock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StockCode = new Field("StockCode", "Mes_Sys_Stock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StockName = new Field("StockName", "Mes_Sys_Stock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StockAddress = new Field("StockAddress", "Mes_Sys_Stock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FactoryCode = new Field("FactoryCode", "Mes_Sys_Stock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Leader = new Field("Leader", "Mes_Sys_Stock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TelPhone = new Field("TelPhone", "Mes_Sys_Stock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Memo = new Field("Memo", "Mes_Sys_Stock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Creater = new Field("Creater", "Mes_Sys_Stock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Sys_Stock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Modifier = new Field("Modifier", "Mes_Sys_Stock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ModifiedTime = new Field("ModifiedTime", "Mes_Sys_Stock", "");
        }
        #endregion
	}
}