//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Stock_ProductInStockItem。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Stock_ProductInStockItem")]
    [Serializable]
    public partial class Mes_Stock_ProductInStockItem : Entity
    {
        #region Model
        private int _ID;
        private string _BillType;
        private string _BillNo;
        private int _ResNum;
        private string _MaterialProNo;
        private string _MaterialCode;
        private string _MaterialSize;
        private int _Num;
        private string _Unit;
        private string _WorkOrderType;
        private string _Memo;
        private string _Creater;
        private DateTime _CreatedTime;
        private string _Modifier;
        private DateTime? _ModifiedTime;
        private string _WorkOrderNumber;
        private int? _ProductInStockID;
        private int? _StockID;
        private int? _AlibraryID;
        private string _Version;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// CP01-成品生产入库单;CP02-半成品入库单
        /// </summary>
        [Field("BillType")]
        public string BillType
        {
            get { return _BillType; }
            set
            {
                this.OnPropertyValueChange("BillType");
                this._BillType = value;
            }
        }
        /// <summary>
        /// 生产入库单明细表
        /// </summary>
        [Field("BillNo")]
        public string BillNo
        {
            get { return _BillNo; }
            set
            {
                this.OnPropertyValueChange("BillNo");
                this._BillNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ResNum")]
        public int ResNum
        {
            get { return _ResNum; }
            set
            {
                this.OnPropertyValueChange("ResNum");
                this._ResNum = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MaterialProNo")]
        public string MaterialProNo
        {
            get { return _MaterialProNo; }
            set
            {
                this.OnPropertyValueChange("MaterialProNo");
                this._MaterialProNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MaterialCode")]
        public string MaterialCode
        {
            get { return _MaterialCode; }
            set
            {
                this.OnPropertyValueChange("MaterialCode");
                this._MaterialCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MaterialSize")]
        public string MaterialSize
        {
            get { return _MaterialSize; }
            set
            {
                this.OnPropertyValueChange("MaterialSize");
                this._MaterialSize = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Num")]
        public int Num
        {
            get { return _Num; }
            set
            {
                this.OnPropertyValueChange("Num");
                this._Num = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Unit")]
        public string Unit
        {
            get { return _Unit; }
            set
            {
                this.OnPropertyValueChange("Unit");
                this._Unit = value;
            }
        }
        /// <summary>
        /// 工单单别
        /// </summary>
        [Field("WorkOrderType")]
        public string WorkOrderType
        {
            get { return _WorkOrderType; }
            set
            {
                this.OnPropertyValueChange("WorkOrderType");
                this._WorkOrderType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Memo")]
        public string Memo
        {
            get { return _Memo; }
            set
            {
                this.OnPropertyValueChange("Memo");
                this._Memo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Creater")]
        public string Creater
        {
            get { return _Creater; }
            set
            {
                this.OnPropertyValueChange("Creater");
                this._Creater = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreatedTime")]
        public DateTime CreatedTime
        {
            get { return _CreatedTime; }
            set
            {
                this.OnPropertyValueChange("CreatedTime");
                this._CreatedTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Modifier")]
        public string Modifier
        {
            get { return _Modifier; }
            set
            {
                this.OnPropertyValueChange("Modifier");
                this._Modifier = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ModifiedTime")]
        public DateTime? ModifiedTime
        {
            get { return _ModifiedTime; }
            set
            {
                this.OnPropertyValueChange("ModifiedTime");
                this._ModifiedTime = value;
            }
        }
        /// <summary>
        /// 工单单号
        /// </summary>
        [Field("WorkOrderNumber")]
        public string WorkOrderNumber
        {
            get { return _WorkOrderNumber; }
            set
            {
                this.OnPropertyValueChange("WorkOrderNumber");
                this._WorkOrderNumber = value;
            }
        }
        /// <summary>
        /// 入库单ID
        /// </summary>
        [Field("ProductInStockID")]
        public int? ProductInStockID
        {
            get { return _ProductInStockID; }
            set
            {
                this.OnPropertyValueChange("ProductInStockID");
                this._ProductInStockID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("StockID")]
        public int? StockID
        {
            get { return _StockID; }
            set
            {
                this.OnPropertyValueChange("StockID");
                this._StockID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AlibraryID")]
        public int? AlibraryID
        {
            get { return _AlibraryID; }
            set
            {
                this.OnPropertyValueChange("AlibraryID");
                this._AlibraryID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Version")]
        public string Version
        {
            get { return _Version; }
            set
            {
                this.OnPropertyValueChange("Version");
                this._Version = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
				_.BillType,
				_.BillNo,
				_.ResNum,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.BillType,
				_.BillNo,
				_.ResNum,
				_.MaterialProNo,
				_.MaterialCode,
				_.MaterialSize,
				_.Num,
				_.Unit,
				_.WorkOrderType,
				_.Memo,
				_.Creater,
				_.CreatedTime,
				_.Modifier,
				_.ModifiedTime,
				_.WorkOrderNumber,
				_.ProductInStockID,
				_.StockID,
				_.AlibraryID,
				_.Version,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._BillType,
				this._BillNo,
				this._ResNum,
				this._MaterialProNo,
				this._MaterialCode,
				this._MaterialSize,
				this._Num,
				this._Unit,
				this._WorkOrderType,
				this._Memo,
				this._Creater,
				this._CreatedTime,
				this._Modifier,
				this._ModifiedTime,
				this._WorkOrderNumber,
				this._ProductInStockID,
				this._StockID,
				this._AlibraryID,
				this._Version,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Mes_Stock_ProductInStockItem");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ID = new Field("ID", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// CP01-成品生产入库单;CP02-半成品入库单
            /// </summary>
            public readonly static Field BillType = new Field("BillType", "Mes_Stock_ProductInStockItem", "CP01-成品生产入库单;CP02-半成品入库单");
            /// <summary>
            /// 生产入库单明细表
            /// </summary>
            public readonly static Field BillNo = new Field("BillNo", "Mes_Stock_ProductInStockItem", "生产入库单明细表");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ResNum = new Field("ResNum", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MaterialProNo = new Field("MaterialProNo", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MaterialCode = new Field("MaterialCode", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MaterialSize = new Field("MaterialSize", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Num = new Field("Num", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Unit = new Field("Unit", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 工单单别
            /// </summary>
            public readonly static Field WorkOrderType = new Field("WorkOrderType", "Mes_Stock_ProductInStockItem", "工单单别");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Memo = new Field("Memo", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Creater = new Field("Creater", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Modifier = new Field("Modifier", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ModifiedTime = new Field("ModifiedTime", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 工单单号
            /// </summary>
            public readonly static Field WorkOrderNumber = new Field("WorkOrderNumber", "Mes_Stock_ProductInStockItem", "工单单号");
            /// <summary>
            /// 入库单ID
            /// </summary>
            public readonly static Field ProductInStockID = new Field("ProductInStockID", "Mes_Stock_ProductInStockItem", "入库单ID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field StockID = new Field("StockID", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field AlibraryID = new Field("AlibraryID", "Mes_Stock_ProductInStockItem", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Version = new Field("Version", "Mes_Stock_ProductInStockItem", "");
        }
        #endregion
    }
}