//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Tra_InStock。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Tra_InStock")]
    [Serializable]
    public partial class Mes_Tra_InStock : Entity
    {
        #region Model
		private int _ID;
		private string _Barcode;
		private string _SN;
		private string _PackSN;
		private string _MaterialProNo;
		private string _MaterialCode;
		private string _WorkOrderType;
		private string _WorkOrderNumber;
		private string _OptName;
		private int _OrgID;
		private DateTime? _ScanTime;
		private string _BillType;
		private string _BillNo;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Barcode")]
		public string Barcode
		{
			get{ return _Barcode; }
			set
			{
				this.OnPropertyValueChange("Barcode");
				this._Barcode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SN")]
		public string SN
		{
			get{ return _SN; }
			set
			{
				this.OnPropertyValueChange("SN");
				this._SN = value;
			}
		}
		/// <summary>
		/// 外箱SN生成原则(YYYYMMDDHHMMSSS)
		/// </summary>
		[Field("PackSN")]
		public string PackSN
		{
			get{ return _PackSN; }
			set
			{
				this.OnPropertyValueChange("PackSN");
				this._PackSN = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialProNo")]
		public string MaterialProNo
		{
			get{ return _MaterialProNo; }
			set
			{
				this.OnPropertyValueChange("MaterialProNo");
				this._MaterialProNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get{ return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 工单类型(WK10-正常工单;WK20-返工工单)
		/// </summary>
		[Field("WorkOrderType")]
		public string WorkOrderType
		{
			get{ return _WorkOrderType; }
			set
			{
				this.OnPropertyValueChange("WorkOrderType");
				this._WorkOrderType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("WorkOrderNumber")]
		public string WorkOrderNumber
		{
			get{ return _WorkOrderNumber; }
			set
			{
				this.OnPropertyValueChange("WorkOrderNumber");
				this._WorkOrderNumber = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OptName")]
		public string OptName
		{
			get{ return _OptName; }
			set
			{
				this.OnPropertyValueChange("OptName");
				this._OptName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OrgID")]
		public int OrgID
		{
			get{ return _OrgID; }
			set
			{
				this.OnPropertyValueChange("OrgID");
				this._OrgID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ScanTime")]
		public DateTime? ScanTime
		{
			get{ return _ScanTime; }
			set
			{
				this.OnPropertyValueChange("ScanTime");
				this._ScanTime = value;
			}
		}
		/// <summary>
		/// CP01-成品生产入库单
		/// </summary>
		[Field("BillType")]
		public string BillType
		{
			get{ return _BillType; }
			set
			{
				this.OnPropertyValueChange("BillType");
				this._BillType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("BillNo")]
		public string BillNo
		{
			get{ return _BillNo; }
			set
			{
				this.OnPropertyValueChange("BillNo");
				this._BillNo = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.Barcode,
				_.SN,
				_.PackSN,
				_.MaterialProNo,
				_.MaterialCode,
				_.WorkOrderType,
				_.WorkOrderNumber,
				_.OptName,
				_.OrgID,
				_.ScanTime,
				_.BillType,
				_.BillNo,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._Barcode,
				this._SN,
				this._PackSN,
				this._MaterialProNo,
				this._MaterialCode,
				this._WorkOrderType,
				this._WorkOrderNumber,
				this._OptName,
				this._OrgID,
				this._ScanTime,
				this._BillType,
				this._BillNo,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Mes_Tra_InStock");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Mes_Tra_InStock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Barcode = new Field("Barcode", "Mes_Tra_InStock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SN = new Field("SN", "Mes_Tra_InStock", "");
            /// <summary>
			/// 外箱SN生成原则(YYYYMMDDHHMMSSS)
			/// </summary>
			public readonly static Field PackSN = new Field("PackSN", "Mes_Tra_InStock", "外箱SN生成原则(YYYYMMDDHHMMSSS)");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialProNo = new Field("MaterialProNo", "Mes_Tra_InStock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "Mes_Tra_InStock", "");
            /// <summary>
			/// 工单类型(WK10-正常工单;WK20-返工工单)
			/// </summary>
			public readonly static Field WorkOrderType = new Field("WorkOrderType", "Mes_Tra_InStock", "工单类型(WK10-正常工单;WK20-返工工单)");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field WorkOrderNumber = new Field("WorkOrderNumber", "Mes_Tra_InStock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OptName = new Field("OptName", "Mes_Tra_InStock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OrgID = new Field("OrgID", "Mes_Tra_InStock", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ScanTime = new Field("ScanTime", "Mes_Tra_InStock", "");
            /// <summary>
			/// CP01-成品生产入库单
			/// </summary>
			public readonly static Field BillType = new Field("BillType", "Mes_Tra_InStock", "CP01-成品生产入库单");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field BillNo = new Field("BillNo", "Mes_Tra_InStock", "");
        }
        #endregion
	}
}