//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Sys_RoleMap。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Sys_RoleMap")]
    [Serializable]
    public partial class Mes_Sys_RoleMap : Entity
    {
        #region Model
        private int _ID;
        private int _Sys_Role_ID;
        private int _Sys_ModuleItem_ID;
        private int? _ButtonRightFlag;
        private int _RecordStatus;
        private string _Creater;
        private DateTime _CreatedTime;
        private string _Modifier;
        private DateTime? _ModifiedTime;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Sys_Role_ID")]
        public int Sys_Role_ID
        {
            get { return _Sys_Role_ID; }
            set
            {
                this.OnPropertyValueChange("Sys_Role_ID");
                this._Sys_Role_ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Sys_ModuleItem_ID")]
        public int Sys_ModuleItem_ID
        {
            get { return _Sys_ModuleItem_ID; }
            set
            {
                this.OnPropertyValueChange("Sys_ModuleItem_ID");
                this._Sys_ModuleItem_ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ButtonRightFlag")]
        public int? ButtonRightFlag
        {
            get { return _ButtonRightFlag; }
            set
            {
                this.OnPropertyValueChange("ButtonRightFlag");
                this._ButtonRightFlag = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("RecordStatus")]
        public int RecordStatus
        {
            get { return _RecordStatus; }
            set
            {
                this.OnPropertyValueChange("RecordStatus");
                this._RecordStatus = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Creater")]
        public string Creater
        {
            get { return _Creater; }
            set
            {
                this.OnPropertyValueChange("Creater");
                this._Creater = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreatedTime")]
        public DateTime CreatedTime
        {
            get { return _CreatedTime; }
            set
            {
                this.OnPropertyValueChange("CreatedTime");
                this._CreatedTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Modifier")]
        public string Modifier
        {
            get { return _Modifier; }
            set
            {
                this.OnPropertyValueChange("Modifier");
                this._Modifier = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ModifiedTime")]
        public DateTime? ModifiedTime
        {
            get { return _ModifiedTime; }
            set
            {
                this.OnPropertyValueChange("ModifiedTime");
                this._ModifiedTime = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.Sys_Role_ID,
				_.Sys_ModuleItem_ID,
				_.ButtonRightFlag,
				_.RecordStatus,
				_.Creater,
				_.CreatedTime,
				_.Modifier,
				_.ModifiedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._Sys_Role_ID,
				this._Sys_ModuleItem_ID,
				this._ButtonRightFlag,
				this._RecordStatus,
				this._Creater,
				this._CreatedTime,
				this._Modifier,
				this._ModifiedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Mes_Sys_RoleMap");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ID = new Field("ID", "Mes_Sys_RoleMap", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Sys_Role_ID = new Field("Sys_Role_ID", "Mes_Sys_RoleMap", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Sys_ModuleItem_ID = new Field("Sys_ModuleItem_ID", "Mes_Sys_RoleMap", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ButtonRightFlag = new Field("ButtonRightFlag", "Mes_Sys_RoleMap", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RecordStatus = new Field("RecordStatus", "Mes_Sys_RoleMap", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Creater = new Field("Creater", "Mes_Sys_RoleMap", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Sys_RoleMap", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Modifier = new Field("Modifier", "Mes_Sys_RoleMap", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ModifiedTime = new Field("ModifiedTime", "Mes_Sys_RoleMap", "");
        }
        #endregion
    }
}