//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Plan_SaleOrder。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Plan_SaleOrder")]
    [Serializable]
    public partial class Mes_Plan_SaleOrder : Entity
    {
        #region Model
        private int _ID;
        private string _OrderType;
        private string _OrderNo;
        private DateTime _OrderDate;
        private int _Num;
        private decimal _OrderAmount;
        private decimal _PaymentAmount;
        private int? _PaymentType;
        private int _OrderStatus;
        private string _Creater;
        private DateTime _CreatedTime;
        private string _Closer;
        private DateTime? _CloseTime;
        private string _Memo;
        private int? _CustomerID;

        /// <summary>
        /// 
        /// </summary>
        [Field("ID")]
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 订单单别
        /// </summary>
        [Field("OrderType")]
        public string OrderType
        {
            get { return _OrderType; }
            set
            {
                this.OnPropertyValueChange("OrderType");
                this._OrderType = value;
            }
        }
        /// <summary>
        /// 订单单号
        /// </summary>
        [Field("OrderNo")]
        public string OrderNo
        {
            get { return _OrderNo; }
            set
            {
                this.OnPropertyValueChange("OrderNo");
                this._OrderNo = value;
            }
        }
        /// <summary>
        /// 订单时间
        /// </summary>
        [Field("OrderDate")]
        public DateTime OrderDate
        {
            get { return _OrderDate; }
            set
            {
                this.OnPropertyValueChange("OrderDate");
                this._OrderDate = value;
            }
        }
        /// <summary>
        /// 订单数量
        /// </summary>
        [Field("Num")]
        public int Num
        {
            get { return _Num; }
            set
            {
                this.OnPropertyValueChange("Num");
                this._Num = value;
            }
        }
        /// <summary>
        /// 订单金额
        /// </summary>
        [Field("OrderAmount")]
        public decimal OrderAmount
        {
            get { return _OrderAmount; }
            set
            {
                this.OnPropertyValueChange("OrderAmount");
                this._OrderAmount = value;
            }
        }
        /// <summary>
        /// 付款金额
        /// </summary>
        [Field("PaymentAmount")]
        public decimal PaymentAmount
        {
            get { return _PaymentAmount; }
            set
            {
                this.OnPropertyValueChange("PaymentAmount");
                this._PaymentAmount = value;
            }
        }
        /// <summary>
        /// 付款方式
        /// </summary>
        [Field("PaymentType")]
        public int? PaymentType
        {
            get { return _PaymentType; }
            set
            {
                this.OnPropertyValueChange("PaymentType");
                this._PaymentType = value;
            }
        }
        /// <summary>
        /// _1-下单;2-关单
        /// </summary>
        [Field("OrderStatus")]
        public int OrderStatus
        {
            get { return _OrderStatus; }
            set
            {
                this.OnPropertyValueChange("OrderStatus");
                this._OrderStatus = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Creater")]
        public string Creater
        {
            get { return _Creater; }
            set
            {
                this.OnPropertyValueChange("Creater");
                this._Creater = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CreatedTime")]
        public DateTime CreatedTime
        {
            get { return _CreatedTime; }
            set
            {
                this.OnPropertyValueChange("CreatedTime");
                this._CreatedTime = value;
            }
        }
        /// <summary>
        /// 关单人
        /// </summary>
        [Field("Closer")]
        public string Closer
        {
            get { return _Closer; }
            set
            {
                this.OnPropertyValueChange("Closer");
                this._Closer = value;
            }
        }
        /// <summary>
        /// 关单时间
        /// </summary>
        [Field("CloseTime")]
        public DateTime? CloseTime
        {
            get { return _CloseTime; }
            set
            {
                this.OnPropertyValueChange("CloseTime");
                this._CloseTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Memo")]
        public string Memo
        {
            get { return _Memo; }
            set
            {
                this.OnPropertyValueChange("Memo");
                this._Memo = value;
            }
        }
        /// <summary>
        /// 客户ID
        /// </summary>
        [Field("CustomerID")]
        public int? CustomerID
        {
            get { return _CustomerID; }
            set
            {
                this.OnPropertyValueChange("CustomerID");
                this._CustomerID = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.OrderType,
				_.OrderNo,
				_.OrderDate,
				_.Num,
				_.OrderAmount,
				_.PaymentAmount,
				_.PaymentType,
				_.OrderStatus,
				_.Creater,
				_.CreatedTime,
				_.Closer,
				_.CloseTime,
				_.Memo,
				_.CustomerID,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._OrderType,
				this._OrderNo,
				this._OrderDate,
				this._Num,
				this._OrderAmount,
				this._PaymentAmount,
				this._PaymentType,
				this._OrderStatus,
				this._Creater,
				this._CreatedTime,
				this._Closer,
				this._CloseTime,
				this._Memo,
				this._CustomerID,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Mes_Plan_SaleOrder");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ID = new Field("ID", "Mes_Plan_SaleOrder", "");
            /// <summary>
            /// 订单单别
            /// </summary>
            public readonly static Field OrderType = new Field("OrderType", "Mes_Plan_SaleOrder", "订单单别");
            /// <summary>
            /// 订单单号
            /// </summary>
            public readonly static Field OrderNo = new Field("OrderNo", "Mes_Plan_SaleOrder", "订单单号");
            /// <summary>
            /// 订单时间
            /// </summary>
            public readonly static Field OrderDate = new Field("OrderDate", "Mes_Plan_SaleOrder", "订单时间");
            /// <summary>
            /// 订单数量
            /// </summary>
            public readonly static Field Num = new Field("Num", "Mes_Plan_SaleOrder", "订单数量");
            /// <summary>
            /// 订单金额
            /// </summary>
            public readonly static Field OrderAmount = new Field("OrderAmount", "Mes_Plan_SaleOrder", "订单金额");
            /// <summary>
            /// 付款金额
            /// </summary>
            public readonly static Field PaymentAmount = new Field("PaymentAmount", "Mes_Plan_SaleOrder", "付款金额");
            /// <summary>
            /// 付款方式
            /// </summary>
            public readonly static Field PaymentType = new Field("PaymentType", "Mes_Plan_SaleOrder", "付款方式");
            /// <summary>
            /// _1-下单;2-关单
            /// </summary>
            public readonly static Field OrderStatus = new Field("OrderStatus", "Mes_Plan_SaleOrder", "_1-下单;2-关单");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Creater = new Field("Creater", "Mes_Plan_SaleOrder", "");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Plan_SaleOrder", "");
            /// <summary>
            /// 关单人
            /// </summary>
            public readonly static Field Closer = new Field("Closer", "Mes_Plan_SaleOrder", "关单人");
            /// <summary>
            /// 关单时间
            /// </summary>
            public readonly static Field CloseTime = new Field("CloseTime", "Mes_Plan_SaleOrder", "关单时间");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Memo = new Field("Memo", "Mes_Plan_SaleOrder", "");
            /// <summary>
            /// 客户ID
            /// </summary>
            public readonly static Field CustomerID = new Field("CustomerID", "Mes_Plan_SaleOrder", "客户ID");
        }
        #endregion
    }
}