//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Plan_Material。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Plan_Material")]
    [Serializable]
    public partial class Mes_Plan_Material : Entity
    {
        #region Model
		private int _ID;
		private string _WorkOrderNumber;
		private string _MaterialProNo;
		private string _MaterialCode;
		private string _Version;
		private string _ProcessCode;
		private string _SubMaterialProNo;
		private string _SubMaterialCode;
		private string _SubMaterialSize;
		private int _Num;
		private string _Unit;
		private int? _ActionStatus;
		private string _ReplacedMaterial;
		private string _Memo;
		private string _Creater;
		private DateTime _CreatedTime;
		private string _Modifier;
		private DateTime? _ModifiedTime;

		/// <summary>
		/// MappingId
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
        [Field("WorkOrderNumber")]
        public string WorkOrderNumber
		{
            get { return _WorkOrderNumber; }
			set
			{
                this.OnPropertyValueChange("WorkOrderNumber");
                this._WorkOrderNumber = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialProNo")]
		public string MaterialProNo
		{
			get{ return _MaterialProNo; }
			set
			{
				this.OnPropertyValueChange("MaterialProNo");
				this._MaterialProNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MaterialCode")]
		public string MaterialCode
		{
			get{ return _MaterialCode; }
			set
			{
				this.OnPropertyValueChange("MaterialCode");
				this._MaterialCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Version")]
		public string Version
		{
			get{ return _Version; }
			set
			{
				this.OnPropertyValueChange("Version");
				this._Version = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ProcessCode")]
		public string ProcessCode
		{
			get{ return _ProcessCode; }
			set
			{
				this.OnPropertyValueChange("ProcessCode");
				this._ProcessCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
        [Field("SubMaterialProNo")]
        public string SubMaterialProNo
		{
            get { return _SubMaterialProNo; }
			set
			{
                this.OnPropertyValueChange("SubMaterialProNo");
                this._SubMaterialProNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
        [Field("SubMaterialCode")]
        public string SubMaterialCode
		{
            get { return _SubMaterialCode; }
			set
			{
                this.OnPropertyValueChange("SubMaterialCode");
                this._SubMaterialCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SubMaterialSize")]
		public string SubMaterialSize
		{
			get{ return _SubMaterialSize; }
			set
			{
				this.OnPropertyValueChange("SubMaterialSize");
				this._SubMaterialSize = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Num")]
		public int Num
		{
			get{ return _Num; }
			set
			{
				this.OnPropertyValueChange("Num");
				this._Num = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Unit")]
		public string Unit
		{
			get{ return _Unit; }
			set
			{
				this.OnPropertyValueChange("Unit");
				this._Unit = value;
			}
		}
		/// <summary>
		/// _0-普通用料;1-临时物料
		/// </summary>
		[Field("ActionStatus")]
		public int? ActionStatus
		{
			get{ return _ActionStatus; }
			set
			{
				this.OnPropertyValueChange("ActionStatus");
				this._ActionStatus = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ReplacedMaterial")]
		public string ReplacedMaterial
		{
			get{ return _ReplacedMaterial; }
			set
			{
				this.OnPropertyValueChange("ReplacedMaterial");
				this._ReplacedMaterial = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Memo")]
		public string Memo
		{
			get{ return _Memo; }
			set
			{
				this.OnPropertyValueChange("Memo");
				this._Memo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Creater")]
		public string Creater
		{
			get{ return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedTime")]
		public DateTime CreatedTime
		{
			get{ return _CreatedTime; }
			set
			{
				this.OnPropertyValueChange("CreatedTime");
				this._CreatedTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Modifier")]
		public string Modifier
		{
			get{ return _Modifier; }
			set
			{
				this.OnPropertyValueChange("Modifier");
				this._Modifier = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ModifiedTime")]
		public DateTime? ModifiedTime
		{
			get{ return _ModifiedTime; }
			set
			{
				this.OnPropertyValueChange("ModifiedTime");
				this._ModifiedTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.WorkOrderNumber,
				_.MaterialProNo,
				_.MaterialCode,
				_.Version,
				_.ProcessCode,
				_.SubMaterialProNo,
				_.SubMaterialCode,
				_.SubMaterialSize,
				_.Num,
				_.Unit,
				_.ActionStatus,
				_.ReplacedMaterial,
				_.Memo,
				_.Creater,
				_.CreatedTime,
				_.Modifier,
				_.ModifiedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._WorkOrderNumber,
				this._MaterialProNo,
				this._MaterialCode,
				this._Version,
				this._ProcessCode,
				this._SubMaterialProNo,
				this._SubMaterialCode,
				this._SubMaterialSize,
				this._Num,
				this._Unit,
				this._ActionStatus,
				this._ReplacedMaterial,
				this._Memo,
				this._Creater,
				this._CreatedTime,
				this._Modifier,
				this._ModifiedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Mes_Plan_Material");
            /// <summary>
			/// MappingId
			/// </summary>
			public readonly static Field ID = new Field("ID", "Mes_Plan_Material", "MappingId");
            /// <summary>
			/// 
			/// </summary>
            public readonly static Field WorkOrderNumber = new Field("WorkOrderNumber", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialProNo = new Field("MaterialProNo", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MaterialCode = new Field("MaterialCode", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Version = new Field("Version", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProcessCode = new Field("ProcessCode", "Mes_Plan_Material", "");

            public readonly static Field SubMaterialProNo = new Field("SubMaterialProNo", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SubMaterialCode = new Field("SubMaterialProNo", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SubMaterialName = new Field("SubMaterialCode", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SubMaterialSize = new Field("SubMaterialSize", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Num = new Field("Num", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Unit = new Field("Unit", "Mes_Plan_Material", "");
            /// <summary>
			/// _0-普通用料;1-临时物料
			/// </summary>
			public readonly static Field ActionStatus = new Field("ActionStatus", "Mes_Plan_Material", "_0-普通用料;1-临时物料");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ReplacedMaterial = new Field("ReplacedMaterial", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Memo = new Field("Memo", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Creater = new Field("Creater", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Modifier = new Field("Modifier", "Mes_Plan_Material", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ModifiedTime = new Field("ModifiedTime", "Mes_Plan_Material", "");
        }
        #endregion
	}
}