//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Sys_Supplier。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Sys_Supplier")]
    [Serializable]
    public partial class Mes_Sys_Supplier : Entity
    {
        #region Model
		private int _ID;
		private string _SupplierCode;
		private string _SupplierName;
		private string _SupplierPrcName;
		private string _Class;
		private string _Address;
		private string _TelPhone;
		private string _DutyPerson;
		private string _Memo;
		private int _Creater;
		private DateTime? _CreatedTime;
		private int? _Modifier;
		private DateTime? _ModifiedTime;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SupplierCode")]
		public string SupplierCode
		{
			get{ return _SupplierCode; }
			set
			{
				this.OnPropertyValueChange("SupplierCode");
				this._SupplierCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SupplierName")]
		public string SupplierName
		{
			get{ return _SupplierName; }
			set
			{
				this.OnPropertyValueChange("SupplierName");
				this._SupplierName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SupplierPrcName")]
		public string SupplierPrcName
		{
			get{ return _SupplierPrcName; }
			set
			{
				this.OnPropertyValueChange("SupplierPrcName");
				this._SupplierPrcName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Class")]
		public string Class
		{
			get{ return _Class; }
			set
			{
				this.OnPropertyValueChange("Class");
				this._Class = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Address")]
		public string Address
		{
			get{ return _Address; }
			set
			{
				this.OnPropertyValueChange("Address");
				this._Address = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("TelPhone")]
		public string TelPhone
		{
			get{ return _TelPhone; }
			set
			{
				this.OnPropertyValueChange("TelPhone");
				this._TelPhone = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DutyPerson")]
		public string DutyPerson
		{
			get{ return _DutyPerson; }
			set
			{
				this.OnPropertyValueChange("DutyPerson");
				this._DutyPerson = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Memo")]
		public string Memo
		{
			get{ return _Memo; }
			set
			{
				this.OnPropertyValueChange("Memo");
				this._Memo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Creater")]
		public int Creater
		{
			get{ return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedTime")]
		public DateTime? CreatedTime
		{
			get{ return _CreatedTime; }
			set
			{
				this.OnPropertyValueChange("CreatedTime");
				this._CreatedTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Modifier")]
		public int? Modifier
		{
			get{ return _Modifier; }
			set
			{
				this.OnPropertyValueChange("Modifier");
				this._Modifier = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ModifiedTime")]
		public DateTime? ModifiedTime
		{
			get{ return _ModifiedTime; }
			set
			{
				this.OnPropertyValueChange("ModifiedTime");
				this._ModifiedTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.SupplierCode,
				_.SupplierName,
				_.SupplierPrcName,
				_.Class,
				_.Address,
				_.TelPhone,
				_.DutyPerson,
				_.Memo,
				_.Creater,
				_.CreatedTime,
				_.Modifier,
				_.ModifiedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._SupplierCode,
				this._SupplierName,
				this._SupplierPrcName,
				this._Class,
				this._Address,
				this._TelPhone,
				this._DutyPerson,
				this._Memo,
				this._Creater,
				this._CreatedTime,
				this._Modifier,
				this._ModifiedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Mes_Sys_Supplier");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Mes_Sys_Supplier", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SupplierCode = new Field("SupplierCode", "Mes_Sys_Supplier", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SupplierName = new Field("SupplierName", "Mes_Sys_Supplier", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SupplierPrcName = new Field("SupplierPrcName", "Mes_Sys_Supplier", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Class = new Field("Class", "Mes_Sys_Supplier", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Address = new Field("Address", "Mes_Sys_Supplier", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TelPhone = new Field("TelPhone", "Mes_Sys_Supplier", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DutyPerson = new Field("DutyPerson", "Mes_Sys_Supplier", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Memo = new Field("Memo", "Mes_Sys_Supplier", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Creater = new Field("Creater", "Mes_Sys_Supplier", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Sys_Supplier", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Modifier = new Field("Modifier", "Mes_Sys_Supplier", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ModifiedTime = new Field("ModifiedTime", "Mes_Sys_Supplier", "");
        }
        #endregion
	}
}