//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Sys.Model
{
    /// <summary>
    /// 实体类Mes_Tec_DeviceInfo。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Mes_Tec_DeviceInfo")]
    [Serializable]
    public partial class Mes_Tec_DeviceInfo : Entity
    {
        #region Model
		private int _ID;
		private string _DeviceCode;
		private string _DeviceName;
		private string _DeviceSize;
		private string _DeviceType;
		private int _DeviceProperty;
		private int? _OrgID;
		private int? _DeviceStatus;
		private byte[] _DeviceImage;
		private DateTime? _AcceptTime;
		private DateTime? _ValidBeginTime;
		private DateTime? _ValidEndTime;
		private string _Creater;
		private DateTime? _CreatedTime;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeviceCode")]
		public string DeviceCode
		{
			get{ return _DeviceCode; }
			set
			{
				this.OnPropertyValueChange("DeviceCode");
				this._DeviceCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeviceName")]
		public string DeviceName
		{
			get{ return _DeviceName; }
			set
			{
				this.OnPropertyValueChange("DeviceName");
				this._DeviceName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeviceSize")]
		public string DeviceSize
		{
			get{ return _DeviceSize; }
			set
			{
				this.OnPropertyValueChange("DeviceSize");
				this._DeviceSize = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeviceType")]
		public string DeviceType
		{
			get{ return _DeviceType; }
			set
			{
				this.OnPropertyValueChange("DeviceType");
				this._DeviceType = value;
			}
		}
		/// <summary>
		/// _1-专用;2-通用
		/// </summary>
		[Field("DeviceProperty")]
		public int DeviceProperty
		{
			get{ return _DeviceProperty; }
			set
			{
				this.OnPropertyValueChange("DeviceProperty");
				this._DeviceProperty = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OrgID")]
		public int? OrgID
		{
			get{ return _OrgID; }
			set
			{
				this.OnPropertyValueChange("OrgID");
				this._OrgID = value;
			}
		}
		/// <summary>
		/// _1-在用;2-停用;3-报废
		/// </summary>
		[Field("DeviceStatus")]
		public int? DeviceStatus
		{
			get{ return _DeviceStatus; }
			set
			{
				this.OnPropertyValueChange("DeviceStatus");
				this._DeviceStatus = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeviceImage")]
		public byte[] DeviceImage
		{
			get{ return _DeviceImage; }
			set
			{
				this.OnPropertyValueChange("DeviceImage");
				this._DeviceImage = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("AcceptTime")]
		public DateTime? AcceptTime
		{
			get{ return _AcceptTime; }
			set
			{
				this.OnPropertyValueChange("AcceptTime");
				this._AcceptTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ValidBeginTime")]
		public DateTime? ValidBeginTime
		{
			get{ return _ValidBeginTime; }
			set
			{
				this.OnPropertyValueChange("ValidBeginTime");
				this._ValidBeginTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ValidEndTime")]
		public DateTime? ValidEndTime
		{
			get{ return _ValidEndTime; }
			set
			{
				this.OnPropertyValueChange("ValidEndTime");
				this._ValidEndTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Creater")]
		public string Creater
		{
			get{ return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatedTime")]
		public DateTime? CreatedTime
		{
			get{ return _CreatedTime; }
			set
			{
				this.OnPropertyValueChange("CreatedTime");
				this._CreatedTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.ID,
				_.DeviceCode,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.DeviceCode,
				_.DeviceName,
				_.DeviceSize,
				_.DeviceType,
				_.DeviceProperty,
				_.OrgID,
				_.DeviceStatus,
				_.DeviceImage,
				_.AcceptTime,
				_.ValidBeginTime,
				_.ValidEndTime,
				_.Creater,
				_.CreatedTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._DeviceCode,
				this._DeviceName,
				this._DeviceSize,
				this._DeviceType,
				this._DeviceProperty,
				this._OrgID,
				this._DeviceStatus,
				this._DeviceImage,
				this._AcceptTime,
				this._ValidBeginTime,
				this._ValidEndTime,
				this._Creater,
				this._CreatedTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Mes_Tec_DeviceInfo");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Mes_Tec_DeviceInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeviceCode = new Field("DeviceCode", "Mes_Tec_DeviceInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeviceName = new Field("DeviceName", "Mes_Tec_DeviceInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeviceSize = new Field("DeviceSize", "Mes_Tec_DeviceInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeviceType = new Field("DeviceType", "Mes_Tec_DeviceInfo", "");
            /// <summary>
			/// _1-专用;2-通用
			/// </summary>
			public readonly static Field DeviceProperty = new Field("DeviceProperty", "Mes_Tec_DeviceInfo", "_1-专用;2-通用");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OrgID = new Field("OrgID", "Mes_Tec_DeviceInfo", "");
            /// <summary>
			/// _1-在用;2-停用;3-报废
			/// </summary>
			public readonly static Field DeviceStatus = new Field("DeviceStatus", "Mes_Tec_DeviceInfo", "_1-在用;2-停用;3-报废");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeviceImage = new Field("DeviceImage", "Mes_Tec_DeviceInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AcceptTime = new Field("AcceptTime", "Mes_Tec_DeviceInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ValidBeginTime = new Field("ValidBeginTime", "Mes_Tec_DeviceInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ValidEndTime = new Field("ValidEndTime", "Mes_Tec_DeviceInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Creater = new Field("Creater", "Mes_Tec_DeviceInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatedTime = new Field("CreatedTime", "Mes_Tec_DeviceInfo", "");
        }
        #endregion
	}
}